In [1]:
import pandas as pd

### reading preproccessed Df

In [347]:
#backup = pd.read_csv("mergedFinOrig.csv")
#import pickle
#pickle.dump(backup,open('FwinrMerged.pkl','wb'))

In [319]:
merged = pd.read_csv("mergedFinOrig.csv")

In [320]:
merged.head()

,title,genres,hit-list,recovery_rate,proCm1,proCm2,WriterName,DirectorName,EditorName,main_lead,co_lead1
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",5,1176.356577,Ingenious Film Partners,Twentieth Century Fox Film Corporation,Min Windle,James Cameron,John Refoua,Sam Worthington,Zoe Saldana
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",3,320.333333,Walt Disney Pictures,Jerry Bruckheimer Films,Katie Greathouse,Gore Verbinski,Craig Wood,Johnny Depp,Orlando Bloom
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",3,359.459024,Columbia Pictures,Danjaq,Hanz Kawson,Sam Mendes,Lee Smith,Daniel Craig,Christoph Waltz
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",3,433.975640,Legendary Pictures,Warner Bros.,Dileep Singh Rathore,Christopher Nolan,Lee Smith,Christian Bale,Michael Caine
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",2,109.284269,Walt Disney Pictures,NaN,Karin Silvestri,Andrew Stanton,Eric Zumbrunnen,Taylor Kitsch,Lynn Collins

### convert all string datas to numerical datas

In [321]:
#Now we'll convert all string datas to numerical datas
merged[merged['recovery_rate']==0]

Empty DataFrame
Columns: [title, genres, hit-list, recovery_rate, proCm1, proCm2, WriterName, DirectorName, EditorName, main_lead, co_lead1]
Index: []

In [322]:
top1 = merged.groupby('DirectorName')['recovery_rate'].max().loc[lambda x: x >= 1300]
top1dir = top1.index.tolist()
top2 = merged.groupby('DirectorName')['recovery_rate'].max().loc[(merged.groupby('DirectorName')['recovery_rate'].max() >= 900) & (merged.groupby('DirectorName')['recovery_rate'].max() < 1300)]
top2dir = top2.index.tolist()
top3 = merged.groupby('DirectorName')['recovery_rate'].max().loc[(merged.groupby('DirectorName')['recovery_rate'].max() >= 500) & (merged.groupby('DirectorName')['recovery_rate'].max() < 900)]
top3dir = top3.index.tolist()
top4 = merged.groupby('DirectorName')['recovery_rate'].max().loc[(merged.groupby('DirectorName')['recovery_rate'].max() >= 250) & (merged.groupby('DirectorName')['recovery_rate'].max() < 500)]
top4dir = top4.index.tolist()
top5 = merged.groupby('DirectorName')['recovery_rate'].max().loc[(merged.groupby('DirectorName')['recovery_rate'].max() >= 130) & (merged.groupby('DirectorName')['recovery_rate'].max() < 250)]
top5dir = top5.index.tolist()
other  = merged.groupby('DirectorName')['recovery_rate'].max().loc[lambda x:x<130]
otherdir =other.index.tolist()
checker = 0
def convertDir(row):
    if row == 'newdirector':
        return 2
    elif row == 'newdirector':
        return 0
    elif row in top1dir:
        return 6
    elif row in top2dir:
        return 5
    elif row in top3dir:
        return 4
    elif row in top4dir:
        return 3
    elif row in top5dir:
        return 2
   # elif row in other:
   #     return 1
    else:
        return 0

merged['latestDir'] = merged['DirectorName'].apply(convertDir)

In [323]:
merged[merged['WriterName']=='']

Empty DataFrame
Columns: [title, genres, hit-list, recovery_rate, proCm1, proCm2, WriterName, DirectorName, EditorName, main_lead, co_lead1, latestDir]
Index: []

In [324]:
#writer

merged = merged[merged['WriterName']!='']


top1w = merged.groupby('WriterName')['recovery_rate'].max().loc[lambda x: x >= 1300]

top1w = top1w.index.tolist()

top2w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 900) & (merged.groupby('WriterName')['recovery_rate'].max() < 1300)]
top2w = top2w.index.tolist()

top3w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 500) & (merged.groupby('WriterName')['recovery_rate'].max() < 900)]
top3w = top3w.index.tolist()
top4w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 250) & (merged.groupby('WriterName')['recovery_rate'].max() < 500)]
top4w = top4w.index.tolist()
top5w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 130) & (merged.groupby('WriterName')['recovery_rate'].max() < 250)]
top5w = top5w.index.tolist()
otherw  = merged.groupby('WriterName')['recovery_rate'].max().loc[lambda x:x<130]
otherw =otherw.index.tolist()




def convertWritr(row):
    #if row == 'newwriter':
    #    return 2
    if row in top1w:
        return 6
    elif row in top2w:
        return 5
    elif row in top3w:
        return 4
    elif row in top4w:
        return 3
    elif row in top5w:
        return 2
    #elif row in otherw:
    #    return 1
    else:
        return 0
    
    

merged['grp_writer'] = merged['WriterName'].apply(convertWritr)

In [325]:
merged[merged['EditorName']=='']

Empty DataFrame
Columns: [title, genres, hit-list, recovery_rate, proCm1, proCm2, WriterName, DirectorName, EditorName, main_lead, co_lead1, latestDir, grp_writer]
Index: []

In [326]:
#Editor


top1E = merged.groupby('EditorName')['recovery_rate'].max().loc[lambda x: x >= 1300]
top1E = top1E.index.tolist()
top2E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 900) & (merged.groupby('EditorName')['recovery_rate'].max() < 1300)]
top2E = top2E.index.tolist()
top3E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 500) & (merged.groupby('EditorName')['recovery_rate'].max() < 900)]
top3E = top3E.index.tolist()
top4E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 250) & (merged.groupby('EditorName')['recovery_rate'].max() < 500)]
top4E = top4E.index.tolist()
top5E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 110) & (merged.groupby('EditorName')['recovery_rate'].max() < 250)]
top5E = top5E.index.tolist()
otherE  = merged.groupby('EditorName')['recovery_rate'].max().loc[lambda x:x<110]
otherE =otherE.index.tolist()
def convertEdtr(row):
    if row=='':
        return 0
    elif row in top1E:
        return 6
    elif row in top2E:
        return 5
    elif row in top3E:
        return 4
    elif row in top4E:
        return 3
    #elif row in top5E:
    #    return 2
   # elif row in otherE:
   #     return 1
    else:
        return 0

merged['grp_Editor'] = merged['EditorName'].apply(convertEdtr)

In [327]:
merged[merged['proCm1']=='']

Empty DataFrame
Columns: [title, genres, hit-list, recovery_rate, proCm1, proCm2, WriterName, DirectorName, EditorName, main_lead, co_lead1, latestDir, grp_writer, grp_Editor]
Index: []

In [328]:
#Producer

top1p  =merged.groupby('proCm1')['recovery_rate'].max().loc[lambda x: x >= 1300]
top1p = top1p.index.tolist()
top2p = merged.groupby('proCm1')['recovery_rate'].max().loc[(merged.groupby('proCm1')['recovery_rate'].max() >= 900) & (merged.groupby('proCm1')['recovery_rate'].max() < 1300)]
top2p = top2p.index.tolist()
top3p = merged.groupby('proCm1')['recovery_rate'].max().loc[(merged.groupby('proCm1')['recovery_rate'].max() >= 500) & (merged.groupby('proCm1')['recovery_rate'].max() < 900)]
top3p = top3p.index.tolist()
top4p = merged.groupby('proCm1')['recovery_rate'].max().loc[(merged.groupby('proCm1')['recovery_rate'].max() >= 250) & (merged.groupby('proCm1')['recovery_rate'].max() < 500)]
top4p = top4p.index.tolist()
top5p = merged.groupby('proCm1')['recovery_rate'].max().loc[(merged.groupby('proCm1')['recovery_rate'].max() >= 200) & (merged.groupby('proCm1')['recovery_rate'].max() < 250)]
top5p = top5p.index.tolist()
otherp  = merged.groupby('proCm1')['recovery_rate'].max().loc[lambda x:x<200]
otherp =otherp.index.tolist()
def convertP1(row):
    if row in top1p:
        return 6
    elif row in top2p:
        return 5
    elif row in top3p:
        return 4
    elif row in top4p:
        return 3
    elif row in top5p:
        return 2
    #elif row in otherp:
    #    return 1
    else:
        return 0
    

merged['grp_proCm1'] = merged['proCm1'].apply(convertP1)
merged['grp_proCm2'] = merged['proCm2'].apply(convertP1)

In [329]:
merged[merged['main_lead']=='']

Empty DataFrame
Columns: [title, genres, hit-list, recovery_rate, proCm1, proCm2, WriterName, DirectorName, EditorName, main_lead, co_lead1, latestDir, grp_writer, grp_Editor, grp_proCm1, grp_proCm2]
Index: []

#Actor
#mergedn2[['main_lead','co_lead1','co_lead2','co_lead3']] = mergedn2['Actors'].str.split(',' ,expand=True)
#mergedn2 = merged[merged['recovery_rate']!=0]

top1at = merged['main_lead'].value_counts().loc[lambda x:x>=21]
top1act = top1at.index.tolist()
top2at = merged['main_lead'].value_counts().loc[(merged['main_lead'].value_counts().loc[lambda x:x>=18]) & (merged['main_lead'].value_counts().loc[lambda x:x<=20])]
top2act = top2at.index.tolist()
top3at = merged['main_lead'].value_counts().loc[(merged['main_lead'].value_counts().loc[lambda x:x>=15]) & (merged['main_lead'].value_counts().loc[lambda x:x<=17])]
top3act = top3at.index.tolist()
top4at = merged['main_lead'].value_counts().loc[(merged['main_lead'].value_counts().loc[lambda x:x>=12]) & (merged['main_lead'].value_counts().loc[lambda x:x<=14])]
top4act = top4at.index.tolist()
top5at = merged['main_lead'].value_counts().loc[(merged['main_lead'].value_counts().loc[lambda x:x>=9]) & (merged['main_lead'].value_counts().loc[lambda x:x<=11])]
top5act = top5at.index.tolist() 
top6at = merged['main_lead'].value_counts().loc[(merged['main_lead'].value_counts().loc[lambda x:x>=6]) & (merged['main_lead'].value_counts().loc[lambda x:x<=8])]
top6act = top6at.index.tolist()
top7at = merged['main_lead'].value_counts().loc[(merged['main_lead'].value_counts().loc[lambda x:x>=3]) & (merged['main_lead'].value_counts().loc[lambda x:x<=5])]
top7act = top7at.index.tolist()
otherat = merged['main_lead'].value_counts().loc[(merged['main_lead'].value_counts().loc[lambda x:x>=1]) & (merged['main_lead'].value_counts().loc[lambda x:x<=2])]
otheract = otherat.index.tolist()

def convertMainLead2(row):
    
    if row in top1act:
        return 8
    elif row in top2act:
        return 7
    elif row in top3act:
        return 6
    elif row in top4act:
        return 5
    elif row in top5act:
        return 4
   #elif row in top6act:
    #    return 3
    #elif row in top7act:
     #   return 2
   #elif row in otheract:
    #    return 1
    else:
        return 0

merged['2ndgrp_mainLead'] = merged['main_lead'].apply(convertMainLead2)
merged['2ndgrp_co_lead1'] = merged['co_lead1'].apply(convertMainLead2)

In [1]:
#Actor
#mergedn2[['main_lead','co_lead1','co_lead2','co_lead3']] = mergedn2['Actors'].str.split(',' ,expand=True)
mergedn2 = merged[merged['recovery_rate']!=0]

top1a = mergedn2.groupby('main_lead')['recovery_rate'].max().loc[lambda x: x >= 1300]
top1ac = top1a.index.tolist()
top2a = mergedn2.groupby('main_lead')['recovery_rate'].max().loc[(mergedn2.groupby('main_lead')['recovery_rate'].max() >= 900) & (mergedn2.groupby('main_lead')['recovery_rate'].max() < 1300)]
top2ac = top2a.index.tolist()
top3a = mergedn2.groupby('main_lead')['recovery_rate'].max().loc[(mergedn2.groupby('main_lead')['recovery_rate'].max() >= 500) & (mergedn2.groupby('main_lead')['recovery_rate'].max() < 900)]
top3ac = top3a.index.tolist()
top4a = mergedn2.groupby('main_lead')['recovery_rate'].max().loc[(mergedn2.groupby('main_lead')['recovery_rate'].max() >= 250) & (mergedn2.groupby('main_lead')['recovery_rate'].max() < 500)]
top4ac = top4a.index.tolist()
top5a = mergedn2.groupby('main_lead')['recovery_rate'].max().loc[(mergedn2.groupby('main_lead')['recovery_rate'].max() >= 130) & (mergedn2.groupby('main_lead')['recovery_rate'].max() < 250)]
top5ac = top5a.index.tolist()
othera  = mergedn2.groupby('main_lead')['recovery_rate'].max().loc[lambda x:x<130]
otherac =othera.index.tolist()

def convertMainLead(row):
    if row in top1ac:
        return 6
    elif row in top2ac:
        return 5
    elif row in top3ac:
        return 4
   # elif row in top4ac:
   #     return 3
   # elif row in top5ac:
   #     return 2
    #elif row in otherac:
    #    return 1
    else:
        return 0

merged['2ndgrp_mainLead'] = mergedn2['main_lead'].apply(convertMainLead)
merged['2ndgrp_co_lead1'] = mergedn2['co_lead1'].apply(convertMainLead)

NameError: name 'merged' is not defined

In [331]:
merged['latestDir'].value_counts()

3    747
4    735
6    600
0    435
2    373
5    342
Name: latestDir, dtype: int64

In [332]:
merged.columns

Index(['title', 'genres', 'hit-list', 'recovery_rate', 'proCm1', 'proCm2',
       'WriterName', 'DirectorName', 'EditorName', 'main_lead', 'co_lead1',
       'latestDir', 'grp_writer', 'grp_Editor', 'grp_proCm1', 'grp_proCm2',
       '2ndgrp_mainLead', '2ndgrp_co_lead1'],
      dtype='object')

In [333]:
merged['grp_writer'].value_counts()

3    879
0    857
2    641
4    464
6    227
5    164
Name: grp_writer, dtype: int64

In [334]:
merged['grp_Editor'].value_counts()

0    1032
4     750
3     598
6     496
5     356
Name: grp_Editor, dtype: int64

In [335]:
merged[merged['WriterName']=='']

Empty DataFrame
Columns: [title, genres, hit-list, recovery_rate, proCm1, proCm2, WriterName, DirectorName, EditorName, main_lead, co_lead1, latestDir, grp_writer, grp_Editor, grp_proCm1, grp_proCm2, 2ndgrp_mainLead, 2ndgrp_co_lead1]
Index: []

In [336]:
import ast
def getGenre(row):
    nn=''
    li = ast.literal_eval(row)
    for dictt in li:
        nn += dictt['name']+','
    return nn.rstrip(',')    
merged['AllGenre'] = merged['genres'].apply(getGenre)

In [337]:
genre_columns = pd.get_dummies(merged['AllGenre'].str.get_dummies(','), prefix='', prefix_sep='').max(level=0, axis=1)

# Concatenate the new genre columns with the original dataframe
merged_new = pd.concat([merged, genre_columns], axis=1)

C:\Users\HP\AppData\Local\Temp\ipykernel_17100\1787979516.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  genre_columns = pd.get_dummies(merged['AllGenre'].str.get_dummies(','), prefix='', prefix_sep='').max(level=0, axis=1)

In [338]:
merged_new.columns

Index(['title', 'genres', 'hit-list', 'recovery_rate', 'proCm1', 'proCm2',
       'WriterName', 'DirectorName', 'EditorName', 'main_lead', 'co_lead1',
       'latestDir', 'grp_writer', 'grp_Editor', 'grp_proCm1', 'grp_proCm2',
       '2ndgrp_mainLead', '2ndgrp_co_lead1', 'AllGenre', 'Action', 'Adventure',
       'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family',
       'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery',
       'Romance', 'Science Fiction', 'Thriller', 'War', 'Western'],
      dtype='object')

In [339]:
x= merged_new.drop(columns =['title','genres','AllGenre','hit-list','recovery_rate','proCm1','proCm2','WriterName', 'DirectorName', 'EditorName', 'main_lead', 'co_lead1'])

In [340]:
y=merged_new['hit-list']

## Machine Learning

In [341]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

best_random_state = 0
best_accuracy = 0

for currstate in range(100):
    X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.25, random_state=currstate)

    randomforest_model = RandomForestClassifier(n_estimators=60)
    randomforest_model.fit(X_train, Y_train)
    y_pred_rf = randomforest_model.predict(X_test)

    # Calculate evaluation metrics for Random Forest
    
    acc_rf = accuracy_score(Y_test, y_pred_rf)
  

    if acc_rf > best_accuracy:
        best_accuracy = acc_rf
        best_random_state = currstate

print('Best Random State:', best_random_state)
print('Best Accuracy:', best_accuracy)
#print('Random State:', currstate)

Best Random State: 66
Best Accuracy: 0.8997524752475248

In [348]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.25, random_state= 66)
randomforest_model = RandomForestClassifier(n_estimators=60)
randomforest_model.fit(X_train, Y_train)
y_pred_rf = randomforest_model.predict(X_test)

    # Calculate evaluation metrics for Random Forest
conf_mat_rf = confusion_matrix(Y_test, y_pred_rf)
acc_rf = accuracy_score(Y_test, y_pred_rf)
precision_rf = precision_score(Y_test, y_pred_rf, average='weighted')
print('Confusion Matrix for Random Forest:')
print(conf_mat_rf)
print('Accuracy for Random Forest:', acc_rf)
print('Precision:', precision_rf)
print()

Confusion Matrix for Random Forest:
[[178  13   5   2   0   1]
 [ 42 181   7   4   0   1]
 [  0   1 201   5   0   0]
 [  0   1   2  94   1   0]
 [  0   0   0   2  26   0]
 [  0   0   0   0   0  41]]
Accuracy for Random Forest: 0.8923267326732673
Precision: 0.8956618458252477

In [349]:
#pickle.dump(randomforest_model,open('FwinrRfmodel.pkl','wb'))

In [343]:
x.columns

Index(['latestDir', 'grp_writer', 'grp_Editor', 'grp_proCm1', 'grp_proCm2',
       '2ndgrp_mainLead', '2ndgrp_co_lead1', 'Action', 'Adventure',
       'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family',
       'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery',
       'Romance', 'Science Fiction', 'Thriller', 'War', 'Western'],
      dtype='object')

In [344]:
def prepare_inputt(latest_dir,writer,editor, main_lead, co_lead1, prd_cmpny1,prd_cmpny2,genre):
    # Convert director name to integer using convertDir function
    #convertDir,convertMainLead,convertWritr,convertEdtr,
   
    latest_dir_encoded = convertDir(latest_dir)

    # Convert writer name to integer using convertWrit function
    grp_writer_encoded = convertWritr(writer)

    # Convert editor name to integer using convertEdtr function
    grp_editor_encoded = convertEdtr(editor)

    # Convert main lead name to integer using convertMainLead function
    grp_main_lead_encoded = convertMainLead(main_lead)

    # Convert co_lead1 name to integer using convertCoLead1 function
    grp_co_lead1_encoded = convertMainLead(co_lead1)

    # Convert production company names to integers using getCmpny function
    grp_pro_cm1_encoded = convertP1(prd_cmpny1)
    grp_pro_cm2_encoded = convertP1(prd_cmpny2)
    
    # Create a DataFrame with the input values
    input_data1 = pd.DataFrame({
        #'budget': [budget],
        #'runtime': [runtime],
        #'no:maleCast': [no_male_cast],
        #'release_month': [release_month],
        #'no:Cast': [no_cast],
        #'no:Crew': [no_crew],
        #'no:keywords':[no_of_keyword_encoded],
        'latestDir': [latest_dir_encoded],
        'grp_writer':[grp_writer_encoded],
        'grp_Editor':[grp_editor_encoded],
        'grp_proCm1':[grp_pro_cm1_encoded],
        'grp_proCm2':[grp_pro_cm2_encoded],
        '2ndgrp_mainLead':[grp_main_lead_encoded],
        '2ndgrp_co_lead1':[grp_co_lead1_encoded]
        
       
    })
   

    # Split the genre string into a list of individual genres
    genres = genre.split(',')

    # Create genre columns and set their values based on the input genres
    genre_columns = ['Action', 'Adventure',
       'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family',
       'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery',
       'Romance', 'Science Fiction', 'Thriller', 'War', 'Western']
    #row
    
    
    genre_values = [1 if genre in genres else 0 for genre in genre_columns]#column
    
    input_data1[genre_columns] = pd.DataFrame([genre_values])
   
    val = randomforest_model.predict(input_data1)[0]
    
    return val

In [345]:
prepare_inputt('Nathan Greno','Min Windle','Lee Smith','Sam Worthington','Zoe Saldana','Twentieth Century Fox Film Corporation','Twentieth Century Fox Film Corporation','Action,Romance,Family')

2

In [346]:
merged.head(20)

,title,genres,hit-list,recovery_rate,proCm1,proCm2,WriterName,DirectorName,EditorName,main_lead,co_lead1,latestDir,grp_writer,grp_Editor,grp_proCm1,grp_proCm2,2ndgrp_mainLead,2ndgrp_co_lead1,AllGenre
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",5,1176.356577,Ingenious Film Partners,Twentieth Century Fox Film Corporation,Min Windle,James Cameron,John Refoua,Sam Worthington,Zoe Saldana,5,5,5,5,6,5,2,"Action,Adventure,Fantasy,Science Fiction"
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",3,320.333333,Walt Disney Pictures,Jerry Bruckheimer Films,Katie Greathouse,Gore Verbinski,Craig Wood,Johnny Depp,Orlando Bloom,4,3,4,6,3,4,2,"Adventure,Fantasy,Action"
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",3,359.459024,Columbia Pictures,Danjaq,Hanz Kawson,Sam Mendes,Lee Smith,Daniel Craig,Christoph Waltz,6,3,4,5,0,4,0,"Action,Adventure,Crime"
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",3,433.975640,Legendary Pictures,Warner Bros.,Dileep Singh Rathore,Christopher Nolan,Lee Smith,Christian Bale,Michael Caine,4,3,4,6,6,4,3,"Action,Crime,Drama,Thriller"
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",2,109.284269,Walt Disney Pictures,NaN,Karin Silvestri,Andrew Stanton,Eric Zumbrunnen,Taylor Kitsch,Lynn Collins,5,5,0,6,0,2,0,"Action,Adventure,Science Fiction"
5,Spider-Man 3,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",3,345.299080,Columbia Pictures,Laura Ziskin Productions,Greg Outcalt,Sam Raimi,Bob Murawski,Tobey Maguire,Kirsten Dunst,6,3,4,5,3,4,3,"Fantasy,Action,Adventure"
6,Tangled,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",2,227.613437,Walt Disney Pictures,Walt Disney Animation Studios,Mark Mitchell,Nathan Greno,Tim Mertens,Zachary Levi,Mandy Moore,2,2,3,6,3,4,3,"Animation,Family"
7,Avengers: Age of Ultron,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",4,501.929891,Marvel Studios,Prime Focus,Jamie Christopher,Joss Whedon,Lisa Lassek,Robert Downey Jr.,Chris Hemsworth,4,4,4,4,0,4,3,"Action,Adventure,Science Fiction"
8,Harry Potter and the Half-Blood Prince,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",3,373.583679,Warner Bros.,Heyday Films,Stuart Wilson,David Yates,Mark Day,Daniel Radcliffe,Rupert Grint,4,3,4,6,0,4,0,"Adventure,Fantasy,Family"
9,Batman v Superman: Dawn of Justice,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",3,349.304078,DC Comics,Atlas Entertainment,Jason Fields,Zack Snyder,David Brenner,Ben Affleck,Henry Cavill,4,3,5,4,3,6,3,"Action,Adventure,Fantasy"
10,Superman Returns,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",2,144.844886,DC Comics,Legendary Pictures,Guy Hendrix Dyas,Bryan Singer,Elliot Graham,Brandon Routh,Kevin Spacey,3,2,3,4,6,2,6,"Adventure,Fantasy,Action,Science Fiction"
11,Quantum of Solace,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",3,293.045364,Eon Productions,NaN,Michael G. Wilson,Marc Forster,Matt Chesse,Daniel Craig,Olga Kurylenko,5,4,5,6,0,4,0,"Adventure,Action,Thriller,Crime"
12,Pirates of the Caribbean: Dead Man's Chest,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",4,532.829906,Walt Disney Pictures,Jerry Bruckheimer Films,Cedric Nicolas-Troyan,Gore Verbinski,Craig Wood,Johnny Depp,Orlando Bloom,4,4,4,6,3,4,2,"Adventure,Fantasy,Action"
13,The Lone Ranger,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",1,35.015651,Walt Disney Pictures,Jerry Bruckheimer Films,Lee Orloff,Gore Verbinski,James Haygood,Johnny Depp,Armie Hammer,4,5,0,6,3,4,0,"Action,Adventure,Western"
14,Man of Steel,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",3,294.598008,Legendary Pictures,Warner Bros.,Carlos Castillon,Zack Snyder,David Brenner,Henry Cavill,Amy Adams,4,3,5,6,6,3,3,"Action,Adventure,Fantasy,Science Fiction"
15,The Chronicles of Narnia: Prince Caspian,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...",2,186.511739,Walt Disney,Walden Media,Manning Tillman,Andrew Adamson,Josh Campbell,Ben Barnes,William Moseley,3,2,0,5,3,2,3,"Adventure,Family,Fantasy"
16,The Avengers,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",4,690.708141,Paramount Pictures,Marvel Studios,Mike Marcuzzi,Joss Whedon,Lisa Lassek,Robert Downey Jr.,Chris Evans,4,4,4,6,4,4,3,"Science Fiction,Action,Adventure"
17,Pirates of the Caribbean: On Stranger Tides,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",3,275.187843,Walt Disney Pictures,Jerry Bruckheimer Films,Lee Orloff,Rob Marshall,Wyatt Smith,Johnny Depp,Penélope Cruz,4,5,3,6,3,4,4,"Adventure,Action,Fantasy"
18,Men in Black 3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",3,277.345234,Amblin Entertainment,Media Magik Entertainment,Mark Aaron Wagner,Barry Sonnenfeld,Don Zimmerman,Will Smith,Tommy Lee Jones,4,4,4,6,0,5,4,"Action,Comedy,Science Fiction"
19,The Hobbit: The Battle of the Five Armies,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",3,382.407915,WingNut Films,New Line Cinema,John Mckay,Peter Jackson,Jabez Olssen,Martin Freeman,Ian McKellen,5,3,5,5,6,3,3,"Action,Adventure,Fantasy"