In [1]:
#Step==3,get mainlead,colead,writer names , arrange them on base of recovery rate
#91% acccuracy

In [548]:
import pandas as pd

In [549]:
merged = pd.read_csv('dupFinalmerged1(uptodir_genre).csv')

In [550]:
merged.head()

,budget,runtime,revenue,no:maleCrew,no:maleCast,release_month,release_dow,release_year,no:Cast,no:Crew,...,Mystery,Romance,Sci-Fi,Sport,Thriller,War,title,Actors,recovery_rate,crew
0,237000000,162.0,2787965087,28,20,12,3,2009,83,153,...,0.0,0.0,0.0,0.0,0.0,0.0,Avatar,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",1176.356577,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,169.0,961000000,15,25,5,5,2007,34,32,...,0.0,0.0,0.0,0.0,0.0,0.0,Pirates of the Caribbean: At World's End,"Johnny Depp, Orlando Bloom, Keira Knightley,Ge...",320.333333,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,148.0,880674609,25,55,10,0,2015,83,155,...,0.0,0.0,0.0,0.0,1.0,0.0,Spectre,"Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...",359.459024,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,165.0,1084939099,37,73,7,0,2012,158,217,...,0.0,0.0,0.0,0.0,1.0,0.0,The Dark Knight Rises,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",433.975640,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,132.0,284139100,25,19,3,2,2012,27,132,...,0.0,0.0,1.0,0.0,0.0,0.0,John Carter,"Taylor Kitsch, Lynn Collins, Willem Dafoe,Sama...",109.284269,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [551]:
merged.columns

Index(['budget', 'runtime', 'revenue', 'no:maleCrew', 'no:maleCast',
       'release_month', 'release_dow', 'release_year', 'no:Cast', 'no:Crew',
       'mainGenre', 'no:keywords', 'prod_company', 'no:femCast', 'latestDir',
       'Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'title',
       'Actors', 'recovery_rate', 'crew'],
      dtype='object')

In [552]:
merged['Actors'][0]

'Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez'

In [610]:
merged[['main_lead','co_lead1','co_lead2','co_lead3']] = merged['Actors'].str.split(',' ,expand=True)

merged['main_lead'] = merged['main_lead'].str.strip()
merged['co_lead1'] = merged['co_lead1'].str.strip()
merged['co_lead2'] = merged['co_lead2'].str.strip()
merged['co_lead3'] = merged['co_lead3'].str.strip()

In [611]:
merged[['main_lead','co_lead1','co_lead2','co_lead3']]

,main_lead,co_lead1,co_lead2,co_lead3
0,Sam Worthington,Zoe Saldana,Sigourney Weaver,Michelle Rodriguez
1,Johnny Depp,Orlando Bloom,Keira Knightley,Geoffrey Rush
2,Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph Fiennes
3,Christian Bale,Tom Hardy,Anne Hathaway,Gary Oldman
4,Taylor Kitsch,Lynn Collins,Willem Dafoe,Samantha Morton
...,...,...,...,...
572,Sarah Butler,Jeff Branson,Andrew Howard,Daniel Franzese
573,Patrick Wilson,Rose Byrne,Ty Simpkins,Lin Shaye
574,Heather Sossaman,Matthew Bohrer,Courtney Halverson,Shelley Hennig
575,Ryan Gosling,Michelle Williams,John Doman,Faith Wladyka
576,Lorenza Izzo,Ariel Levy,Aaron Burns,Kirby Bliss Blanton

In [555]:
#now we'll classify these actor to certain groups just like wed did for directors

In [556]:
merged = merged[merged['recovery_rate']!=0]

In [557]:
merged['recovery_rate'].shape

(577,)

In [558]:
merged['recovery_rate'].sort_values(ascending=False)

573    6467.276667
574    6288.209000
547    3927.289431
570    3500.000000
541    3085.487787
          ...
567      12.965520
302       6.648660
561       5.114615
568       1.651010
560       1.263158
Name: recovery_rate, Length: 577, dtype: float64

In [559]:
merged.groupby('main_lead')['recovery_rate'].max()

main_lead
Aaron Paul               307.996418
Aaron Taylor-Johnson     343.531796
Adam Sandler             591.533698
Adrien Brody             315.622032
Alex Pettyfer            288.985660
                           ...
Woody Allen              430.852241
Zac Efron                681.337380
Zach Galifianakis       1312.201769
Zachary Gordon           504.669987
Zooey Deschanel          809.636453
Name: recovery_rate, Length: 296, dtype: float64

In [560]:
#start converting actors to groups based on rec.rate

In [561]:
top1 = merged.groupby('main_lead')['recovery_rate'].max().loc[lambda x: x >= 1300]
top1dir = top1.index.tolist()
top1dir[0:10]
top1

main_lead
Benedict Cumberbatch    1668.255057
Channing Tatum          2388.879586
Colin Firth             2761.410327
Dakota Johnson          1427.515320
Dev Patel               2519.403627
Ellen Page              3085.487787
Ethan Hawke             2977.620900
Heather Sossaman        6288.209000
Jennifer Lopez          1310.646375
Natalie Portman         2521.567162
Olivia DeJonge          1969.001240
Patrick Wilson          6467.276667
Ryan Reynolds           1350.194791
Sandra Bullock          1563.149949
Seth Rogen              1489.763333
Shailene Woodley        2559.723617
Shameik Moore           2569.540143
Ulrich Mühe             3500.000000
Ward Horton             3927.289431
Zach Galifianakis       1312.201769
Name: recovery_rate, dtype: float64

In [562]:
#To get name bw 2 codnitions
top2 = merged.groupby('main_lead')['recovery_rate'].max().loc[(merged.groupby('main_lead')['recovery_rate'].max() >= 900) & (merged.groupby('main_lead')['recovery_rate'].max() < 1300)]
top2dir = top2.index.tolist()
top2dir[0:10]
top2

main_lead
Anna Kendrick           991.400669
Anne Hathaway           933.003126
Bradley Cooper          979.708162
Chiwetel Ejiofor        935.000000
Chris Hemsworth         913.726119
Chris Pratt            1009.019207
Dylan O'Brien          1024.470179
Ellar Coltrane         1108.725000
Emilia Clarke          1039.725375
Emma Stone              936.903812
Jackie Chan            1135.194475
Jason Bateman          1179.573060
Jennifer Lawrence       921.614256
Jessica Chastain        976.651807
Kenny Wormald           976.041488
Kristen Stewart        1061.126014
Lake Bell              1088.377440
Liam Neeson             907.322272
Louis C.K.             1167.944411
Mark Wahlberg          1098.736630
Matthew McConaughey    1103.965700
Meryl Streep           1172.772379
Mila Kunis              919.680370
Quinton Aaron          1066.235548
Sam Worthington        1176.356577
Steve Carell           1277.318270
Teresa Palmer           900.143510
Name: recovery_rate, dtype: float64

In [563]:
#To get name bw 2 codnitions
top3 = merged.groupby('main_lead')['recovery_rate'].max().loc[(merged.groupby('main_lead')['recovery_rate'].max() >= 500) & (merged.groupby('main_lead')['recovery_rate'].max() < 900)]
top3dir = top3.index.tolist()
top3dir[0:10]
top3

main_lead
Adam Sandler       591.533698
Ben Affleck        605.459611
Blake Lively       700.592694
Brad Pitt          541.320728
Brie Larson        590.029300
                      ...
Vin Diesel         500.910140
Will Smith         558.322355
Zac Efron          681.337380
Zachary Gordon     504.669987
Zooey Deschanel    809.636453
Name: recovery_rate, Length: 68, dtype: float64

In [565]:
#To get name bw 2 codnitions
top4 = merged.groupby('main_lead')['recovery_rate'].max().loc[(merged.groupby('main_lead')['recovery_rate'].max() >= 250) & (merged.groupby('main_lead')['recovery_rate'].max() < 500)]
top4dir = top4.index.tolist()
top4dir[0:10]
top4

main_lead
Aaron Paul              307.996418
Aaron Taylor-Johnson    343.531796
Adrien Brody            315.622032
Alex Pettyfer           288.985660
Amy Adams               400.573708
                           ...
Tom Cruise              479.112676
Tom Hardy               252.572227
Travis Fimmel           271.048239
Will Ferrell            485.572274
Woody Allen             430.852241
Name: recovery_rate, Length: 100, dtype: float64

In [567]:
#To get name bw 2 codnitions
top5 = merged.groupby('main_lead')['recovery_rate'].max().loc[(merged.groupby('main_lead')['recovery_rate'].max() >= 100) & (merged.groupby('main_lead')['recovery_rate'].max() < 250)]
top5dir = top5.index.tolist()
top5dir[0:10]
top5

main_lead
Alexander Skarsgård    198.190589
Alexandra Daddario     236.209725
Alice Englert          100.086897
Alicia Vikander        245.796093
Amanda Bynes           169.445795
Asa Butterfield        163.332504
Ben Barnes             120.188014
Brandon Routh          144.844886
Bryce Dallas Howard    221.069751
Chadwick Boseman       237.550533
Charlie Cox            193.657180
Christopher Plummer    214.508690
Dakota Fanning         207.660663
Daniel Brühl           237.493747
Dennis Quaid           172.839438
Diego Luna             194.874212
Edgar Ramírez          127.351153
Edward Norton          217.287543
Emily Browning         109.503051
Ewan McGregor          133.827329
Gabriella Wilde        170.389600
Hilary Swank           196.051352
Idris Elba             226.446059
Jackie Earle Haley     142.506910
Jaden Smith            187.571636
James Marsden          138.177742
Jason Statham          163.916702
Jim Sturgess           199.494854
Joaquin Phoenix        205.875004
Joel Kinnaman          202.240804
John Travolta          180.900016
Josh Hartnett          208.551411
Josh Hutcherson        229.311772
Keegan-Michael Key     137.108847
Kevin Costner          187.849996
Kodi Smit-McPhee       120.728065
Kristen Connolly       221.620267
Liam Hemsworth         236.170870
Lily Collins           150.942368
Lorenza Izzo           136.668900
Lubna Azabal           104.468206
Lucas Black            186.433285
Mandy Moore            227.613437
Mark Rylance           130.961135
Naomi Watts            107.014283
Neve Campbell          242.846715
Nicolas Cage           207.943994
Nicole Kidman          206.797147
Quvenzhané Wallis      205.879717
Rachel Weisz           143.885517
Ron Perlman            188.691839
Sam Rockwell           195.202080
Scott Eastwood         185.333179
Sean Faris             208.137155
Sean Penn              175.334838
Taron Egerton          200.664348
Taylor Kitsch          109.284269
Thomas Haden Church    219.836275
Vince Vaughn           245.492629
Name: recovery_rate, dtype: float64

In [568]:
other  = merged.groupby('main_lead')['recovery_rate'].max().loc[lambda x:x<100]
otherdir =other.index.tolist()
other

main_lead
Anton Yelchin      64.407420
Bryan Cranston     61.747232
Carmen Electra     56.437136
Casey Affleck      63.196485
Cillian Murphy     64.035606
Clive Owen          1.263158
Connor Paolo        5.114615
Danny McBride      52.347972
Jack Huston        94.061311
Julianne Moore     92.052304
Justin Long        65.239464
Karl Urban         82.075484
Kit Harington      90.639716
Levi Miller        85.592213
Luke Wilson         1.651010
Michael Shannon    34.512678
Mickey Rourke      60.627102
Paul Giamatti      56.380225
Rainn Wilson       12.965520
Sarah Butler       28.640450
Tilda Swinton      86.270600
Vinnie Jones       23.554847
Name: recovery_rate, dtype: float64

In [569]:
def convertMainLead(row):
    if row in top1dir:
        return 6
    elif row in top2dir:
        return 5
    elif row in top3dir:
        return 4
    elif row in top4dir:
        return 3
    elif row in top5dir:
        return 2
    elif row in other:
        return 1
    else:
        return 0

merged['grp_mainLead'] = merged['main_lead'].apply(convertMainLead)

In [570]:
merged['grp_mainLead'].unique()

array([5, 4, 2, 3, 6, 1], dtype=int64)

In [577]:
merged['grp_mainLead'].value_counts()

4    201
3    171
5     74
2     68
6     41
1     22
Name: grp_mainLead, dtype: int64

In [578]:
# well do the same thing for co-lead1 also..
#now most of the famous names would be included in made list 
#, so we dont want to do same proccess of forming grouplist again.

In [612]:
def convertCoLead(row):
    if row in top1dir:
        return 6
    elif row in top2dir:
        return 5
    elif row in top3dir:
        return 4
    elif row in top4dir:
        return 3
    elif row in top5dir:
        return 2
    elif row in other:
        return 1
    else:
        return 0

merged['grp_co_lead1'] = merged['co_lead1'].apply(convertCoLead)

In [603]:
merged['co_lead1'].head()

0         Zoe Saldana
1       Orlando Bloom
2     Christoph Waltz
3           Tom Hardy
4        Lynn Collins
Name: co_lead1, dtype: object

In [613]:
merged['grp_co_lead1'].unique()

array([0, 3, 4, 5, 2, 6, 1], dtype=int64)

In [614]:
merged['grp_co_lead1'].value_counts()

0    350
3     71
4     63
5     33
2     28
6     18
1     14
Name: grp_co_lead1, dtype: int64

In [615]:
def convertCoLead2(row):
    if row in top1dir:
        return 6
    elif row in top2dir:
        return 5
    elif row in top3dir:
        return 4
    elif row in top4dir:
        return 3
    elif row in top5dir:
        return 2
    elif row in other:
        return 1
    else:
        return 0

merged['grp_co_lead2'] = merged['co_lead2'].apply(convertCoLead)

In [616]:
merged['co_lead2'].isna().sum()

0

In [617]:
merged['grp_co_lead2'].value_counts()

0    416
3     57
4     43
5     21
2     19
1     11
6     10
Name: grp_co_lead2, dtype: int64

In [585]:
#now we want to extract the writters name and arrange to groups

In [586]:
merged['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [621]:
import ast
def getWriter(row):
    nn=''
    li = ast.literal_eval(row)
    for dictt in li:
        if((dictt['job'])=='Writer' or 'Screenplay'):
            nn = dictt['name']
    return nn

merged['WriterName'] = merged['crew'].apply(getWriter)

In [622]:
merged[merged['WriterName']=='']

Empty DataFrame
Columns: [budget, runtime, revenue, no:maleCrew, no:maleCast, release_month, release_dow, release_year, no:Cast, no:Crew, mainGenre, no:keywords, prod_company, no:femCast, latestDir, Action, Adventure, Aniimation, Biography, Comedy, Crime, Drama, Family, Fantasy, History, Horror, Music, Musical, Mystery, Romance, Sci-Fi, Sport, Thriller, War, title, Actors, recovery_rate, crew, main_lead, co_lead1, co_lead2, co_lead3, grp_mainLead, grp_co_lead1, grp_co_lead2, WriterName, grp_writer]
Index: []

[0 rows x 47 columns]

In [623]:
merged['WriterName'].value_counts()

Karin Silvestri          8
Anthony Rizzo            5
Brian Avery              5
Luca Marco Paracels      4
Junyoung Jang            4
                        ..
Kathryn Prince           1
Rachel Constantinescu    1
Kenneth Hunter           1
Susan E. Levin           1
Lavinia Zetina           1
Name: WriterName, Length: 506, dtype: int64

In [624]:
#Now we have to categorise them on the basis of the movies recovery rate

In [625]:
#we'll make  lists of writers

In [626]:
merged.groupby('WriterName')['recovery_rate'].max()

WriterName
Aaron Dem          420.084861
Aaron Hurvitz      110.050450
Adam Anders         79.224817
Adam B. Stern      551.145639
Adam Moos          220.412432
                      ...
William Scharpf    678.531918
Yoko Nobushi       800.425020
Yona Prost         207.660663
Yuhon Ng           187.571636
Zoe Freed           61.747232
Name: recovery_rate, Length: 506, dtype: float64

In [627]:
top1w = merged.groupby('WriterName')['recovery_rate'].max().loc[lambda x: x >= 1300]
print(top1w)
top1w = top1w.index.tolist()
top1w[0:10]
top1w

WriterName
Arielle Toelke            2590.414633
Atlin Mitchell            1350.194791
Casey Rieboldt            1310.646375
Claire Dodgson            1563.149949
Dane Wilson               1969.001240
Doug Fairall              2559.723617
Ejaz Shalkh               2519.403627
Geraldine Needle          3927.289431
Germaine Franco           2569.540143
James Markham Hall Jr.    1489.763333
Kathleen Switzer          6288.209000
Kellie Roy                6467.276667
Lee Morse                 2388.879586
Luke Kalteux              1312.201769
Mark McNeill              2446.154931
Martin Zillger            3500.000000
Max Martin                1427.515320
Melanie Jones             2977.620900
Michael Kreple            3085.487787
Steve Morphew             2761.410327
Suzie Shearer             1668.255057
Tony Arnaud               2521.567162
Name: recovery_rate, dtype: float64

['Arielle Toelke',
 'Atlin Mitchell',
 'Casey Rieboldt',
 'Claire Dodgson',
 'Dane Wilson',
 'Doug Fairall',
 'Ejaz Shalkh',
 'Geraldine Needle',
 'Germaine Franco',
 'James Markham Hall Jr.',
 'Kathleen Switzer',
 'Kellie Roy',
 'Lee Morse',
 'Luke Kalteux',
 'Mark McNeill',
 'Martin Zillger',
 'Max Martin',
 'Melanie Jones',
 'Michael Kreple',
 'Steve Morphew',
 'Suzie Shearer',
 'Tony Arnaud']

In [628]:
top2w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 900) & (merged.groupby('WriterName')['recovery_rate'].max() < 1300)]
top2w = top2w.index.tolist()
top2w[0:10]
top2w

['Aida Swinson',
 'Dave Pultz',
 'Esther Vivante',
 'James Buxton',
 'Jeffrey Cassidy',
 'Jim DeFelice',
 'Judy Richter',
 'Karin Silvestri',
 'Kevin Reynolds',
 'Kim Garman',
 'Kurt and Bart',
 'Laurin Guthrie',
 'Lee Orloff',
 'Marc Lema',
 'Mary H. Ellis',
 'Matt Thompson',
 'Michele Ziegler',
 'Mike Revell',
 'Min Windle',
 'Nick Smith',
 'Robert Taylor',
 'Ryan Bradley',
 'Régis Desissert',
 'Samantha Ward',
 'Scott Moore',
 'Stephenie Meyer',
 'Stig Anderson',
 'Vanessa Lapato',
 'Warwick Sadler']

In [629]:
top3w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 500) & (merged.groupby('WriterName')['recovery_rate'].max() < 900)]
top3w = top3w.index.tolist()
top3w[0:10]
top3w

['Adam B. Stern',
 'Alex Bailey',
 'Alex Madison',
 'Anne Goelz',
 'Antongiulio Frulio',
 'Ardis Cohen',
 'Arun Ram-Mohan',
 'Bert Van Brande',
 'Brian Avery',
 'Carrie-Ann Banner',
 'Cedric Nicolas-Troyan',
 'Charlie Watson',
 'Chris W. Johnson',
 'Christine Bodelot',
 'Claudia Pascual',
 "Conor O'Sullivan",
 'Craig Baxley Jr',
 'Craig Branham',
 'Daniel A. Parker',
 'David Winkler',
 'Debbie Holbrook',
 'Di Bennett',
 'Diane Durant',
 'Dogu Abaris',
 'Donald Frazee',
 'Earl A. Hibbert',
 'Edward Lassak',
 'Elizabeth Wright Shapiro',
 'Gabe Hilfer',
 'Gerald Sullivan',
 'Harry Harrison',
 'Hershel Cohen',
 'Hugo Dominguez',
 'Ian Blum',
 'Jacqueline Oknaian',
 'Jacques Paradis',
 'Jamie Christopher',
 'Jan Brun',
 'Jason Soudah',
 'Jaume Roures',
 'Jax Martin',
 'Jean-Francois Lachapelle',
 'Jeremiah Sweeney',
 'Jerry Kurland',
 'Jessie Erikson',
 'John Bartnicki',
 'John Quartel',
 'Johnny Gidcomb',
 'Joseph Basile',
 'Junyoung Jang',
 'Ken Saville',
 'Kimberly di Bonaventura',
 'Kris Cole',
 'Loudon Wainwright III',
 'Louise Parker',
 'Luca Marco Paracels',
 'Maggie Rodford',
 'Marcy Lavender',
 'Mark Aaron Wagner',
 'Mark Paterson',
 'Martín Hernández',
 'Melanie Deforrest',
 'Michelle Wright',
 'Mike Marcuzzi',
 'Morgan Gjovik',
 'Nima Nourizadeh',
 'Peter Amies',
 'Renee Fontana',
 'Richard Davies',
 'Ron Finn',
 'Ronald G. Muhammad',
 'Ryan Kirby',
 'Saygin Saral',
 'Sean Gilhooly',
 'Sheila Nash',
 'Sian Milne',
 'Son Lux',
 'Taylor Stewart',
 'Terry Claborn',
 'Thierry Baucheron',
 'Tony Mecca',
 'Tracy Boyd',
 'Tricia Linklater',
 'Tyler Nelson',
 'Virginia Burton',
 'William Scharpf',
 'Yoko Nobushi']

In [630]:
top4w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 250) & (merged.groupby('WriterName')['recovery_rate'].max() < 500)]
top4w = top4w.index.tolist()
top4w[0:10]
top4w

['Aaron Dem',
 'Adriaan Engelbrecht',
 'Allen Coulter',
 'Amol Parulekar',
 'Andrea Carter',
 'Andrew Kinney',
 'Andrew Mortelliti',
 'Andy Hass',
 'Andy Ross',
 'Angela Mooar',
 'Anthony Di Ninno',
 'Anthony Rizzo',
 'Anthony Seyler',
 'Beauxregard Neylon',
 'Bert Berry',
 'Brian Beard',
 'Brian Courchine',
 'Carlos Castillon',
 'Carlos Fernandez Puertolas',
 'Caroline Barclay',
 'Catherine Lavoie',
 'Charles Maloy',
 'Charles Randolph',
 'Chrissy Metge',
 'Christopher Kaller',
 'Christopher Norris',
 'Christy Beam',
 'Clare Sera',
 'Clay Cullen',
 'Coco Francini',
 'Colin Akoon',
 'Colleen Kelsall',
 'Corey Deist',
 'Damien Drew',
 'Dan Redford',
 'Daniel Frisch',
 'Daniel Pemberton',
 'Daren Hicks',
 'Darius Khondji',
 'Darrin Smith',
 'Dave Levine',
 'Davi Russo',
 'David A. Newman',
 'David Greene',
 'David McKeown',
 'David Neumann',
 'Dean Wright',
 'Dhumal Sagar',
 'Diane Collins',
 'Dileep Singh Rathore',
 'Dinesh K. Bishnoi',
 'Dominic Lewis',
 'Dottie Starling',
 'Eliot Milbourn',
 'Elspeth Cassar',
 'Emilio Ghorayeb',
 'Emily Berger',
 'Erika Abberton',
 'Farrah Fox-Collis',
 'Frank Hildebrand',
 'Frank Reina',
 'Fred Wolf',
 'Freesia Pearson',
 'Gage Lansky',
 'Gareth Cousins',
 'Gary Goldman',
 'Gigi Oeri',
 'Greg Basser',
 'Greg Outcalt',
 'Gwenaelle Larpent',
 'Hanz Kawson',
 'Harold Parker',
 'Hauk Olafsson',
 'Heather R. Dumas',
 'Hjörtur Grétarsson',
 'Howard R. Campbell',
 'Inbal Weinberg',
 'Jack Dolman',
 'James K. Lee',
 'James Keys',
 'Jamey Pryde',
 'Jason Fields',
 'Jatinder Singh Manhas',
 'Jeff Cassidy',
 'Jeff Kinney',
 'Jeremy Hindle',
 'Jeremy Stewart',
 'Jessica Drake',
 'Jessica Wolff',
 'Joey McFarland',
 'John Cheng',
 'John Isbell',
 'John Mckay',
 'John To',
 'Jonathan Bell',
 'Jose L. Rodriguez',
 'José R. Varona',
 'Judd Wild',
 'Julien Lasbleiz',
 'June Diane Raphael',
 'Karen Foster (V)',
 'Katherine McCormack',
 'Kathryn Prince',
 'Katie Dippold',
 'Katie Greathouse',
 'Ken Wills',
 'Kenneth Hunter',
 'Khris Bennett',
 'Kleber Souza',
 'Kurt Volk',
 'Lara Khachooni',
 'Laura Leganza Reynolds',
 'Leslie Webb',
 'Lindsay Greitzer',
 'Lisa Zagoria',
 'Lois Lowry',
 'Lorette Leblanc',
 'Louise McCarthy',
 'Louise Vesth',
 'Lucy Laliberte',
 'Luis Montemayor',
 'Mark Edward Wright',
 'Mark Fitzgerald',
 'Mark Scoon',
 'Martin Corbett',
 'Matt Blades',
 'Matt Johnson',
 'Meagan Costello',
 'Melissa Stack',
 'Michael Arthur',
 'Michael G. Wilson',
 'Mirela Rupic',
 'Nancy Keslar',
 'Natalie Taylor Smith',
 'Natalie Young',
 'Nick London',
 'Nicky Knowles',
 'Nina Jacobson',
 'Nori Chia',
 'Pablo Perona',
 'Pat Sito',
 'Paul Eliopoulos',
 'Paul Parsons',
 'Paul Wernick',
 'Pauline Hume',
 'Peter Doctor',
 'Petur Hliddal',
 'Randy Cantor',
 'Renee J. Vaca',
 'Richard Brener',
 'Roberto Ortiz',
 'Rodney Rothman',
 'Rosalie Carew',
 'Rui Gang Li',
 'Ryan Thurbon',
 'Sabine Varnes',
 'Sapphire',
 'Scheryl W Brown',
 'Scott Menzies',
 'Sean Button',
 'Season Kent',
 'Shawn M Gray',
 'Sonny Surowiec',
 'Spencer Stone',
 'Spiro Carras',
 'Stana Slosserova',
 'Stephen Gabis',
 'Stephen Hutchinson',
 'Stewart Whelan',
 'Stuart Wilson',
 'Susan E. Levin',
 'Tammy Fearing',
 'Tamsin Jeffrey',
 'Teresa Carriker-Thayer',
 'Todd Sheidenberger',
 'Todd Spears',
 'Tom Carson',
 'Tom Davis',
 'Tom Nelson',
 'Tom Wolfe',
 'Travis Tohill',
 'Trent Hara',
 'Tyler Allison',
 'Tyler DeLisle',
 'Una Hill',
 'Wayne Jaworskyj',
 'Wei M. Zhao',
 'Wendy Jacobson',
 'Wendy Williams',
 'Will Fetters',
 'William Paul Clark']

In [631]:
top5w = merged.groupby('WriterName')['recovery_rate'].max().loc[(merged.groupby('WriterName')['recovery_rate'].max() >= 100) & (merged.groupby('WriterName')['recovery_rate'].max() < 250)]
print(top5w)
top5w = top5w.index.tolist()
top5w[0:10]
top5w

WriterName
Aaron Hurvitz             110.050450
Adam Moos                 220.412432
Adam Peters               184.369227
Alexander Yves Brunner    120.728065
Allan Jenkins             121.307845
                             ...
Venessa De Anda           205.875004
Vera Zivny                176.100049
Wade Wilson               199.494854
Yona Prost                207.660663
Yuhon Ng                  187.571636
Name: recovery_rate, Length: 136, dtype: float64

['Aaron Hurvitz',
 'Adam Moos',
 'Adam Peters',
 'Alexander Yves Brunner',
 'Allan Jenkins',
 'Anastasia Masaro',
 'Andrew Palmer',
 'Andy Schuhler',
 'Anna Hawkins',
 'Anna Zenowicz',
 'Aoife Warren',
 'Arthur Farkas',
 'Atsushi Nishijima',
 'Baic Zong',
 'Barbara Darragh',
 'Ben Wilson',
 'Bradley Porter',
 'Brendan Gunn',
 'Callum Davison',
 'Carole A. Kenneally',
 'Caroline Kelly',
 'Charlie Bolwell',
 'Chris Henchy',
 'Chris Street',
 'Christine Tisseau Giraudel',
 'Chuck Rock',
 'Dan McDermott',
 'Daniel Boccoli',
 'Daniel Martinez',
 'Darryl Pryor',
 'David Dalessandro',
 'David Kennedy',
 'Dennis Colvin',
 'Donald Murphy',
 "Dustin O'Halloran",
 'Eleanor Nett',
 'Elise G. Viola',
 'Elliott Eisman',
 'Emily Streetz',
 'Erik Classen',
 'Evan Fisher',
 'Eve Light Honthaner',
 'Gemma La Mana',
 'George Fisher',
 'Gerd Nefzer',
 'Guy Hendrix Dyas',
 'Géza Kovács',
 'Heather Noble',
 'Hermione Byrt',
 'Ian McFadyen',
 'Imre Orosz',
 'J. Mills Goodloe',
 'Jane Walker',
 'Jason Smilovic',
 'Jennifer Cornwell',
 'Joe Iemola',
 'Joel Zadak',
 'John Bramley',
 'John Trejo',
 'Jonathan Eusebio',
 'Josh Henson',
 'Joshua Safran',
 'Justin Lanchbury',
 'Karen Iverson',
 'Karen Swallow',
 'Karma Hijjawi',
 'Kaz Rassoulzadegan',
 'Ken Gorrell',
 'Kristin Martini',
 'Kristine Kelly',
 'Lavinia Zetina',
 'Lizzy Jane Klein',
 'Lora Laing',
 'Lori Guidroz',
 'Lori Wyant',
 'Louis Phillips',
 'Lydia Bensimmon',
 'Lynn Younglove',
 'Maja Aro',
 'Malosi Leonard',
 'Mariela Zapata',
 'Marija Markovic',
 'Mark Mitchell',
 'Mark N Tompkins',
 'Mark S. Wright',
 'Mark Weingarten',
 'Matsune Suzuki',
 'Max Joseph',
 'Mike Rosenstein',
 'Molly Kamrath',
 'Nicole Eckenroad',
 'Nicole Oguchi',
 'Nikki Clapp',
 'Pablo Azorin',
 'Paul Machliss',
 'Paul Prokop',
 'Peter Czernin',
 'Peter Lindsay',
 'Rachel Constantinescu',
 'Rachel Wyn Dunn',
 'Rafy',
 'Rebecca Holmes',
 'Rebecca Milton',
 'Rob Harris',
 'Robert Zuckerman',
 'Rodriguez',
 'Rupert Maconick',
 'Ryan Smith',
 'Sandra Mooney',
 'Sarah Campbell',
 'Sarah Nettinga',
 'Scott Kravitz',
 'Shane Gross',
 'Sharon Davis',
 'Siggy Ferstl',
 'Simon Valdimir Varela',
 'Stanley D. Williams',
 'Stefano Marino',
 'Stephen Barton',
 'Suzanne Stokes-Munton',
 'Suzy Freeman',
 'Sylvaine Dufaux',
 'T. Justin Ross',
 'Tegan Jones',
 'Terry Blyther',
 'Timmy Thompson',
 'Tom Wood',
 'Tony Baldridge',
 'Tricia Wood',
 'Ugla Hauksdóttir',
 'Valentin Toncu',
 'Venessa De Anda',
 'Vera Zivny',
 'Wade Wilson',
 'Yona Prost',
 'Yuhon Ng']

In [632]:
otherw  = merged.groupby('WriterName')['recovery_rate'].max().loc[lambda x:x<100]
otherw =otherw.index.tolist()
otherw

['Adam Anders',
 'Alex Fenn',
 'Amanda Williams',
 'Ana Dávila',
 'Anwen Bull',
 'Brian Hathaway',
 'Cara Leibovitz',
 'Carmel Musgrove',
 'Caroline Labrie',
 'Chris Murphy',
 'Daniel Hammond',
 'Daniel S. Levine',
 'David Warren',
 'Deborah Hecht',
 'Demelza Cronin',
 'Donald Burghardt',
 'Donna Martin',
 'Elvis Jones',
 'Gerald Green',
 'Heidi Falconer',
 'Jason Potter',
 'Jeff Buhler',
 'John D. Kretschmer',
 'Jon Mone',
 'Karel Jiran',
 'Kenny Yates',
 'Kimberly Asa',
 'Larry Long',
 'Mark Burnett',
 'Michael Nelson',
 'Nigel Godrich',
 'Peter Hicks',
 'Phil Langone',
 'Shaamilla Noordien',
 'Shara Storch',
 'Simon Davis',
 'Stephani DeLuca',
 'Steven Marshall',
 'Vicki Stefanopoulos',
 'Warren Ellis',
 'Zoe Freed']

In [633]:
merged[merged['WriterName']=='']

Empty DataFrame
Columns: [budget, runtime, revenue, no:maleCrew, no:maleCast, release_month, release_dow, release_year, no:Cast, no:Crew, mainGenre, no:keywords, prod_company, no:femCast, latestDir, Action, Adventure, Aniimation, Biography, Comedy, Crime, Drama, Family, Fantasy, History, Horror, Music, Musical, Mystery, Romance, Sci-Fi, Sport, Thriller, War, title, Actors, recovery_rate, crew, main_lead, co_lead1, co_lead2, co_lead3, grp_mainLead, grp_co_lead1, grp_co_lead2, WriterName, grp_writer]
Index: []

[0 rows x 47 columns]

In [634]:
def convertWritr(row):
    if row in top1w:
        return 6
    elif row in top2w:
        return 5
    elif row in top3w:
        return 4
    elif row in top4w:
        return 3
    elif row in top5w:
        return 2
    elif row in otherw:
        return 1
    else:
        return 0

merged['grp_writer'] = merged['WriterName'].apply(convertWritr)

In [635]:
merged['grp_writer'].value_counts()

3    216
2    140
4    113
1     42
5     39
6     27
Name: grp_writer, dtype: int64

In [602]:
#we'll look for Editor

In [446]:
merged['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [447]:
def getEditor(row):
    nn=''
    li=ast.literal_eval(row)
    for dictt in li:
        if dictt['department']=='Editing':
            nn=dictt['name']
    return nn

merged['EditorName'] = merged['crew'].apply(getEditor)

In [448]:
merged[merged['EditorName']=='']

,budget,runtime,revenue,no:maleCrew,no:maleCast,release_month,release_dow,release_year,no:Cast,no:Crew,...,main_lead,co_lead1,co_lead2,co_lead3,grp_mainLead,grp_co_lead1,grp_co_lead2,WriterName,grp_writer,EditorName
28,200000000,104.0,743559607,8,16,6,3,2013,24,13,...,Billy Crystal,John Goodman,Steve Buscemi,Helen Mirren,3,0,0,Peter Doctor,3,
33,200000000,114.0,219851172,15,14,6,3,2011,23,47,...,Ryan Reynolds,Blake Lively,Peter Sarsgaard,Mark Strong,6,0,0,Scheryl W Brown,3,
39,105000000,143.0,351040419,9,16,5,4,2013,31,18,...,Leonardo DiCaprio,Carey Mulligan,Joel Edgerton,Tobey Maguire,4,0,0,Damien Drew,3,
44,185000000,93.0,538983207,12,6,6,3,2012,15,44,...,Kelly Macdonald,Billy Connolly,Emma Thompson,Julie Walters,3,0,0,Laura Leganza Reynolds,3,
54,145000000,112.0,401128639,5,10,7,1,2008,15,17,...,Brendan Fraser,Jet Li,Maria Bello,Michelle Yeoh,3,0,0,Lorette Leblanc,3,
57,175000000,118.0,302469017,12,16,8,1,2009,23,23,...,Dennis Quaid,Channing Tatum,Marlon Wayans,Adewale Akinnuoye-Agbaje,2,0,0,Jeremy Stewart,3,
62,180000000,97.0,758539785,3,15,5,2,2014,82,14,...,Angelina Jolie,Elle Fanning,Sharlto Copley,Lesley Manville,3,0,0,Dhumal Sagar,3,
84,150000000,107.0,373062864,5,23,4,1,2009,63,8,...,Hugh Jackman,Liev Schreiber,Ryan Reynolds,Danny Huston,4,0,0,Judd Wild,3,
97,145000000,95.0,521170825,6,13,1,5,2016,34,34,...,Jack Black,Bryan Cranston,Dustin Hoffman,Angelina Jolie,3,0,0,Rui Gang Li,3,
98,145000000,133.0,694713380,13,10,12,2,2011,16,28,...,Tom Cruise,Jeremy Renner,Simon Pegg,Paula Patton,3,0,0,Luca Marco Paracels,4,
120,130000000,95.0,321887208,7,14,10,3,2010,23,14,...,Will Ferrell,Jonah Hill,Brad Pitt,Tina Fey,3,0,0,Andy Schuhler,2,
135,115000000,114.0,164602163,5,25,4,2,2016,42,7,...,Chris Hemsworth,Jessica Chastain,Charlize Theron,Emily Blunt,5,0,0,Cedric Nicolas-Troyan,4,
136,125000000,101.0,477200000,10,13,8,3,2014,28,54,...,Megan Fox,Will Arnett,William Fichtner,Noel Fisher,3,0,0,Jeremy Stewart,3,
164,95000000,102.0,114178613,11,15,12,4,2014,35,55,...,Ben Barnes,Julianne Moore,Jeff Bridges,Alicia Vikander,2,0,0,Chris Street,2,
174,100000000,125.0,94061311,5,9,8,2,2016,19,8,...,Jack Huston,Toby Kebbell,Rodrigo Santoro,Nazanin Boniadi,1,0,0,Mark Burnett,1,
177,90000000,106.0,174578751,10,11,8,2,2013,22,29,...,Logan Lerman,Alexandra Daddario,Brandon T. Jackson,Nathan Fillion,3,0,0,Atlin Mitchell,6,
179,90000000,96.0,484635760,10,8,4,6,2011,13,16,...,Jesse Eisenberg,Anne Hathaway,George Lopez,Karen Disher,4,0,0,Arun Ram-Mohan,4,
186,60000000,112.0,47664559,5,13,7,1,2010,30,7,...,Michael Cera,Mary Elizabeth Winstead,Kieran Culkin,Alison Pill,4,0,0,Nigel Godrich,1,
189,85000000,120.0,160388063,12,8,7,4,2008,11,14,...,Ron Perlman,Selma Blair,Doug Jones,John Alexander,2,0,0,Géza Kovács,2,
199,80000000,89.0,473226958,1,13,9,0,2015,22,9,...,Adam Sandler,Andy Samberg,Selena Gomez,Kevin James,4,0,0,Tony Mecca,4,
206,50000000,117.0,90450008,8,18,7,4,2007,152,23,...,John Travolta,Queen Latifah,Nikki Blonsky,Michelle Pfeiffer,2,0,0,Paul Prokop,2,
208,80000000,102.0,271430189,3,9,6,3,2010,20,3,...,Adam Sandler,Salma Hayek,Kevin James,Chris Rock,4,0,0,Fred Wolf,3,
231,61000000,157.0,441809770,14,32,12,1,2012,208,46,...,Hugh Jackman,Russell Crowe,Anne Hathaway,Amanda Seyfried,4,0,0,Mark Paterson,4,
247,70000000,113.0,171844840,3,11,9,5,2009,18,6,...,Vince Vaughn,Malin Akerman,Jon Favreau,Jason Bateman,2,0,0,Christine Tisseau Giraudel,2,
249,58000000,111.0,71664962,6,17,10,2,2010,29,13,...,Bruce Willis,Helen Mirren,Morgan Freeman,Mary-Louise Parker,3,0,0,Tricia Wood,2,
254,60000000,105.0,50549107,12,13,1,2,2014,29,31,...,Chris Pine,Kevin Costner,Keira Knightley,Kenneth Branagh,3,0,0,Matt Johnson,3,
257,61000000,124.0,95696996,7,12,3,3,2007,16,10,...,Mark Wahlberg,Michael Peña,Rhona Mitra,Danny Glover,5,0,0,Karin Silvestri,5,
258,60000000,100.0,469160692,9,18,2,3,2014,35,82,...,Chris Pratt,Will Ferrell,Elizabeth Banks,Will Arnett,5,0,0,Ryan Kirby,4,
260,60000000,130.0,90565421,4,15,8,2,2013,22,12,...,Lily Collins,Jamie Campbell Bower,Robert Sheehan,Jemima West,2,0,0,Anthony Rizzo,3,
289,44000000,125.0,63327201,10,10,3,4,2013,36,19,...,Saoirse Ronan,Max Irons,Jake Abel,Diane Kruger,4,0,0,Melanie Deforrest,4,
291,44000000,125.0,63327201,10,10,3,4,2013,36,19,...,Kang-ho Song,Hee-Bong Byun,Hae-il Park,Doona Bae,4,0,0,Melanie Deforrest,4,
293,11000000,119.0,88489643,10,10,7,3,2006,36,19,...,Saoirse Ronan,Max Irons,Jake Abel,Diane Kruger,4,0,0,Melanie Deforrest,4,
295,11000000,119.0,88489643,10,10,7,3,2006,36,19,...,Kang-ho Song,Hee-Bong Byun,Hae-il Park,Doona Bae,4,0,0,Melanie Deforrest,4,
298,49900000,102.0,26121638,10,13,4,4,2011,27,11,...,Danny McBride,Natalie Portman,James Franco,Rasmus Hardiker,1,0,0,Jon Mone,1,
306,40000000,117.0,123494610,8,8,5,2,2014,31,9,...,Adam Sandler,Drew Barrymore,Wendi McLendon-Covey,Kevin Nealon,4,0,0,Clare Sera,3,
328,40000000,109.0,196781193,2,5,4,2,2014,16,4,...,Cameron Diaz,Leslie Mann,Kate Upton,Nikolaj Coster-Waldau,3,0,0,Melissa Stack,3,
336,40000000,111.0,97138686,8,5,4,0,2011,24,11,...,Neve Campbell,Courteney Cox,David Arquette,Lucy Hale,2,0,0,Karin Silvestri,5,
341,33000000,108.0,20645327,9,10,9,1,2009,24,15,...,Dennis Quaid,Ben Foster,Cam Gigandet,Antje Traue,2,0,0,Ana Dávila,1,
346,10000000,110.0,47536959,1,2,11,4,2009,22,3,...,Gabourey Sidibe,Mo'Nique,Paula Patton,Mariah Carey,3,0,0,Sapphire,3,
354,37000000,122.0,392616625,0,14,11,3,2008,26,3,...,Kristen Stewart,Robert Pattinson,Billy Burke,Sarah Clarke,5,0,0,Stephenie Meyer,5,
359,38000000,110.0,252276927,3,17,12,2,2010,31,17,...,Jeff Bridges,Matt Damon,Hailee Steinfeld,Josh Brolin,4,0,0,Craig Branham,4,
363,35000000,109.0,150483765,4,9,7,3,2011,16,4,...,Mila Kunis,Justin Timberlake,Patricia Clarkson,Jenna Elfman,5,0,0,David A. Newman,3,
382,35000000,97.0,116980662,9,20,1,3,2013,36,19,...,Nicholas Hoult,Teresa Palmer,John Malkovich,Analeigh Tipton,3,0,0,David McKeown,3,
385,30000000,89.0,114663461,2,9,1,4,2009,28,4,...,Kate Hudson,Anne Hathaway,Candice Bergen,Bryan Greenberg,3,0,0,June Diane Raphael,3,
394,30000000,123.0,64352607,4,12,10,3,2009,24,8,...,Christopher Plummer,Lily Cole,Heath Ledger,Andrew Garfield,2,0,0,Anastasia Masaro,2,
406,28000000,108.0,16374328,4,6,2,3,2016,22,13,...,Lily James,Sam Riley,Jack Huston,Bella Heathcote,4,0,0,Chris Murphy,1,
417,26000000,117.0,35926213,5,13,10,3,2014,34,5,...,James Marsden,Michelle Monaghan,Luke Bracey,Liana Liberato,2,0,0,J. Mills Goodloe,2,
422,25000000,101.0,99357138,4,5,4,3,2012,11,4,...,Zac Efron,Taylor Schilling,Blythe Danner,Riley Thomas Stewart,4,0,0,Will Fetters,3,
439,23600000,88.0,102391382,7,8,10,2,2009,16,9,...,Jesse Eisenberg,Emma Stone,Woody Harrelson,Abigail Breslin,4,0,0,Paul Wernick,3,
445,17000000,111.0,73244881,3,7,4,4,2012,17,3,...,Woody Allen,Penélope Cruz,Jesse Eisenberg,Ellen Page,3,0,0,Darius Khondji,3,
453,20000000,100.0,183936074,2,6,7,3,2016,33,4,...,Mila Kunis,Kathryn Hahn,Kristen Bell,Christina Applegate,5,0,0,Scott Moore,5,
462,20000000,103.0,34077920,2,7,2,2,2014,38,7,...,Gabriella Wilde,Alex Pettyfer,Bruce Greenwood,Robert Patrick,2,0,0,Joshua Safran,2,
465,20000000,106.0,30426096,2,16,9,4,2011,37,7,...,Anna Faris,Chris Evans,Ari Graynor,Blythe Danner,3,0,0,Dottie Starling,3,
472,21000000,99.0,72417394,3,13,3,4,2011,19,4,...,Zachary Gordon,Devon Bostick,Robert Capron,Rachael Harris,4,0,0,Jeff Kinney,3,
502,15000000,107.0,59389433,2,12,3,2,2011,31,6,...,Anne Hathaway,Jim Sturgess,Patricia Clarkson,Tom Mison,5,0,0,Nina Jacobson,3,
510,16000000,117.0,77000000,1,14,3,3,2016,47,6,...,Jennifer Garner,Kylie Rogers,Martin Henderson,Brighton Sharbino,3,0,0,Christy Beam,3,
544,700000,103.0,17986781,0,7,6,4,2015,20,3,...,Shameik Moore,Tony Revolori,Kiersey Clemons,Kimberly Elise,6,0,0,Germaine Franco,6,
550,4900000,81.0,44107032,9,5,7,3,2016,15,17,...,Teresa Palmer,Gabriel Bateman,Maria Bello,Billy Burke,5,0,0,Samantha Ward,5,
561,650000,98.0,33245,6,7,9,3,2010,14,18,...,Connor Paolo,Nick Damici,Kelly McGillis,Gregory Jones,1,0,0,Amanda Williams,1,
568,30000000,84.0,495303,4,15,9,4,2006,53,7,...,Luke Wilson,Maya Rudolph,Dax Shepard,Terry Crews,1,0,0,Michael Nelson,1,

In [449]:
#now we want group these Editors to specific groups

In [450]:
merged.groupby('EditorName')['recovery_rate'].max()

EditorName
                   2569.540143
Aaron Marshall       92.228460
Adam Brailsford    1167.944411
Adam Ohl            222.621389
Adam Robinson       634.485680
                      ...
Wyatt Jones         302.538689
Wyatt Smith         306.890955
Yvan Lucas          455.901500
Zach Staenberg      434.826490
Zene Baker          393.879131
Name: recovery_rate, Length: 421, dtype: float64

In [451]:
top1E = merged.groupby('EditorName')['recovery_rate'].max().loc[lambda x: x >= 1300]
top1E = top1E.index.tolist()
top1E[0:10]
top1E

['',
 'Claire Dodgson',
 'Clay Rawlins',
 'David Grant',
 'Debra Neil-Fisher',
 'Dennis Alaniz',
 'Dylan Quirt',
 'Ejaz Shalkh',
 'Frédéric Thoraval',
 'Greg Borkman',
 'Jeff Smithwick',
 'Jonathan Collard',
 'Justin Dzuban',
 'Kirk M. Morri',
 'Lisa Gunning',
 'Luke Franco Ciarrocch',
 'Matthew G. Carson',
 'Michel Aller',
 'Olivia Retzer',
 'Peter Gvozdas',
 'Richie Roefaro',
 'Steven Soderbergh']

In [452]:
#To get name bw 2 codnitions
top2E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 900) & (merged.groupby('EditorName')['recovery_rate'].max() < 1300)]
top2E = top2E.index.tolist()
top2E[0:10]
top2E

['Adam Brailsford',
 'Angela Hackner',
 'Bud S. Smith',
 'Christopher S. Capp',
 'Dave Pultz',
 'Elliot Greenberg',
 'Frank Smathers',
 'John C. Stuver',
 'John Wilson',
 'Katy Wood',
 'Kris Cole',
 'Lesley Walker',
 'Mark Livolsi',
 'Martin Pensa',
 'Marvin Hall',
 'Michele Conroy',
 'Nancy Richardson',
 'P.J. Burch',
 'Parke Gregg',
 'Paul Hirsch',
 'Robert Chen',
 'Susan Littenberg',
 'Thom Noble',
 'Vanessa Lapato']

In [453]:
#To get name bw 2 codnitions
top3E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 500) & (merged.groupby('EditorName')['recovery_rate'].max() < 900)]
top3E = top3E.index.tolist()
top3E[0:10]
top3E

['Adam Robinson',
 'Akrivi Fili',
 'Alan Edward Bell',
 'Alex Olivares',
 'Alex Portin',
 'Alisa Lepselter',
 'Andrew Marcus',
 'Angela Hemingway',
 'Anne McCabe',
 'Barney Pilling',
 'Bill Pankow',
 'Billy Fox',
 'Brent White',
 'Byron Wilson',
 'Carolyn Calvert',
 'Chris Dickens',
 'Chris Lebenzon',
 'Craig Wood',
 'Crispin Struthers',
 'David Orr',
 'David Zimmerman',
 'Debs Richardson',
 'Devon Miller',
 'Douglas Crise',
 'Gary Lam',
 'Hakan Warn',
 'Halima K. Gilliam',
 'Helen Luttrell',
 'Hershel Cohen',
 'James Herbert',
 'Jeff Draheim',
 'Jeff Groth',
 'Jennifer Lame',
 'Jennifer Vecchiarello',
 'Jimmy Fusil',
 'Joel Negron',
 'John Breinholt',
 'John Quartel',
 'Justin W. Walker',
 'Keith Henderson',
 'Kevin Pavlovic',
 'Kevin Tent',
 'Kim Sun-min',
 'Larry Kemp',
 'Laura Harris Atkinson',
 'Lauren Hadaway',
 'Lea Morement',
 'Lee Smith',
 'Liam Ford',
 'Lisa Zeno Churgin',
 'Mark Day',
 'Mark Keady',
 'Marshall Winn',
 'Mary Jo Markey',
 'Matt Breitenbach',
 'Michael L. Sale',
 'Miguel Rivera',
 'Mike Selemon',
 'Monique Eissing',
 'Morgan Gjovik',
 'Nathan Nugent',
 'Niven Howie',
 'Omar Hassan-Reep',
 'Peter Amies',
 'Peter Lambert',
 'Rachael Tate',
 'Robert Leighton',
 'Robert Ulrich',
 'Roger Barton',
 'Sean Albertson',
 'Sebastian Perez-Burchard',
 'Stuart Baird',
 'Teri E. Dorman',
 'Terry Claborn',
 'Thomas Jones',
 'Tim Squyres',
 'Tyler Nelson',
 'Ulrika Akander',
 'William Kerr']

In [454]:
#To get name bw 2 codnitions
top4E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 250) & (merged.groupby('EditorName')['recovery_rate'].max() < 500)]
top4E = top4E.index.tolist()
top4E[0:10]
top4E

['Alexa Zimmerman',
 'Alexander Berner',
 'Amy Pawlowski',
 'Andrew Mondshein',
 'Barbara Jean Kearney',
 'Barry Alexander Brown',
 'Baxter',
 'Ben Cox',
 'Billy Hobson',
 'Bob Murawski',
 'Brad Semenoff',
 'Brian Beard',
 'Brian Chumney',
 'Brian Scott Olds',
 'C.K. Horness',
 'Cameron Steenhagen',
 'Carlos Castillon',
 'Carlos Puente',
 'Chris Gridley',
 'Chris Regan',
 'Christos Voutsinas',
 'Colby Parker Jr.',
 'Colin Patton',
 'Conrad Buff IV',
 'Craig Alpert',
 'Dallis Anderson',
 'Dan Lebental',
 'Dan Muscarella',
 'Dan Zimmerman',
 'Darrin Navarro',
 'David Alonzo',
 'David Brenner',
 'David Rosenbloom',
 'Dean Zimmerman',
 'Debra Chiate',
 'Debra L. Tennant',
 'Derek Eby',
 'Devin Sterling',
 'Don Zimmerman',
 'Donald Likovich',
 'Dylan Firshein',
 'Dylan Tichenor',
 'Eliot Milbourn',
 'Eric Kissack',
 'Ethan Coen',
 'Ethan Maniquis',
 "Fabio D'Amico",
 'Fran Amaro',
 'Fred Rosenberg',
 'G.W. Brown',
 'George Chavez',
 'George Folsey Jr.',
 'Greg Tillman',
 'Gregory Perler',
 'Gwenaelle Larpent',
 'Harold Parker',
 'Harrison Meyle',
 'Hermione Byrt',
 'Hoon H. Kim',
 'Hughes Winborne',
 'Hugo Weng',
 'Jabez Olssen',
 'James Beshears',
 'Jamie Gross',
 'Jason Canovas',
 'Jason Fields',
 'Javier Marcheselli',
 'Jay Deuby',
 'Jeff Betancourt',
 'Jeff Freeman',
 'Jeff Halsey',
 'Jeff Richardson',
 'Jim Brookshire',
 'Jim May',
 'Joe Walker',
 'John Gilroy',
 'John Mckay',
 'John Refoua',
 'John To',
 'Jonathan Null',
 'Julie Feiner',
 'Justin Ngy Tran',
 'Kate Baird',
 'Ken Terry',
 'Kenny Becker',
 'Kenny G. Krauss',
 'Kevin Nolting',
 'Kim Foscato',
 'Kim Honeyman',
 'Kimberly Boritz',
 'Lara Johnston',
 'Lara Khachooni',
 'Lee Wimer',
 'Leslie Webb',
 'Malcolm Jamieson',
 'Mandy Arnold',
 'Mark Sahagun',
 'Markus Czyzewski',
 'Martin Corbett',
 'Matt Chesse',
 'Matt Coby',
 'Matthew Schmidt',
 'Matthieu Dallaporta',
 'Meagan Costello',
 'Melissa Kent',
 'Michael A. Webber',
 'Michael Berenbaum',
 'Michael Kahn',
 'Michael LaFond',
 'Michelle Pazer',
 'Molly Malene Stensgaard',
 'Nicholas Breslin',
 'Nick Fletcher',
 'Nona Khodai',
 'Paul Parsons',
 'Paul Rubell',
 'Paul Zucker',
 'Paula Anhesini',
 'Pearce Roemer',
 'Peter Boyle',
 'Philippe Majdalani',
 'Pietro Scalia',
 'Richard B. Molina',
 'Robert Benedict',
 'Robert Troy',
 'Rudy Lopez',
 'Russell Farmarco',
 'Salvatore Catanzaro',
 'Samuel D. Pollard',
 'Serena Warner',
 'Shae Salmon',
 'Steven Kemper',
 'Steven Rosenblum',
 'Susan Dawes',
 'Tamsin Jeffrey',
 'Thomas Calderon',
 'Tia Nolan',
 'Timothy Alverson',
 'Toby Francis-Bruce',
 'Tom Costain',
 'Tom Davis',
 'Tom Muldoon',
 'Tracy Adams',
 'Troy Takaki',
 'Tyler Ruocco',
 'Vince Filippone',
 'Wayne Wahrman',
 'William Paley',
 'William Steinkamp',
 'Wyatt Jones',
 'Wyatt Smith',
 'Yvan Lucas',
 'Zach Staenberg',
 'Zene Baker']

In [455]:
#To get name bw 2 codnitions
top5E = merged.groupby('EditorName')['recovery_rate'].max().loc[(merged.groupby('EditorName')['recovery_rate'].max() >= 100) & (merged.groupby('EditorName')['recovery_rate'].max() < 250)]
top5E = top5E.index.tolist()
top5E[0:10]
top5E

['Adam Ohl',
 'Adam Wolfe',
 'Ahren Shaw',
 'Andrew Hulme',
 'Andy Kaplan',
 'Anne V. Coates',
 'Arturo Sosa',
 'Benjamin Beardwood',
 'Bob Ducsay',
 'Branka Mrkic',
 'Bruce Stubblefield',
 'Carole A. Kenneally',
 'Catherine Haight',
 'Catriona Richardson',
 'Changju Kim',
 'Cheryl Nardi',
 'Christine Kim',
 'Christopher Murrie',
 'Claus Wehlisch',
 'Daniel Boccoli',
 'Daniel P. Hanley',
 'Dave Muscat',
 'David A. Arnold',
 'David A. Cohen',
 'David Moritz',
 'David V. Butler',
 'Debra Weinfeld',
 'Dody Dorn',
 'Donnie Creighton',
 'Eddie Hamilton',
 'Elliot Graham',
 'Elliott Eisman',
 "Emilie O'Connor",
 'Emily Streetz',
 'Eric Zumbrunnen',
 'Erik Jessen',
 'Erik Rogers',
 'Evan Fisher',
 'Gemma McKeon',
 'Greg Hayden',
 'Guillaume Battistelli',
 'Guillaume Girard',
 'Heather Goodwin',
 'Heidi Tebo',
 'Howard E. Smith',
 'James Morioka',
 'James Spencer',
 'Jane Winkles',
 'Jason Ballantine',
 'Jill Bogdanowicz',
 'Jill Purdy',
 'Joe Gallagher',
 'John Gilbert',
 'John Wright',
 'Jon Gregory',
 'Jon Harris',
 'Jonny Winograd',
 'Joseph Kirkland',
 'Julia Wong',
 'Julian Clarke',
 'Julian Smirke',
 'Karen Cruces',
 'Kat Thomas',
 'Katia Boutin',
 'Kaz Rassoulzadegan',
 'Kenneth Marsten',
 'Kevin Smith',
 'Kim Drummond',
 'Laurence Johnson',
 'Luke Borghi',
 'Malcolm Fife',
 'Mark Burton',
 'Mark Yoshikawa',
 'Martin Walsh',
 'Matt Blackshear',
 'Meghan L. Noble',
 'Melissa Remenarich',
 'Michael Cipriano',
 'Michael Hertlein',
 'Michael Jablow',
 'Missy Papageorge',
 'Nicholas Monsour',
 'Nicholas Renbeck',
 'Nick Monton',
 'Nick Moore',
 'Nicolas Gaster',
 'Patrick J. Smith',
 'Paul Machliss',
 'Paul Tothill',
 'Pete Beaudreau',
 'Peter Honess',
 'Peter McNulty',
 'Plummy Tucker',
 'Randy Bricker',
 'Richard Francis-Bruce',
 'Rick Derby',
 'Rob Farris',
 'Robert Duffy',
 'Robert E. Phillips',
 'Ron Patane',
 'Sacha Walker',
 'Sarah Flack',
 'Siggy Ferstl',
 'Stan Salfas',
 'Stephanie Johnson',
 'Stuart Levy',
 'Terel Gibson',
 'Tim Mertens',
 'Toska Hartmann',
 'Tracey Wadmore-Smith',
 'Vincent Tabaillon',
 'William Hoy']

In [456]:
otherE  = merged.groupby('EditorName')['recovery_rate'].max().loc[lambda x:x<100]
otherE =otherE.index.tolist()
otherE

['Aaron Marshall',
 'Alex Fenn',
 'Annie Johnson',
 'Barbara Tulliver',
 'Ben Tat',
 'Caitlin Tartaro',
 'Chris Gill',
 'Chris Patterson',
 'Cory Hamilton',
 'Curtiss Clayton',
 'Daniel Duncan',
 'Danny Rafic',
 'David Smith',
 'Emanuele Giraldo',
 'Emma E. Hickox',
 'Eric Kench',
 'Evan Henke',
 'Jennifer Apel',
 'Joe Bini',
 'Leslie Jones',
 'Maciek Malish',
 'Mako Kamitsuna',
 'Matthew M. North',
 'Paul Dawber',
 'Peck Prior',
 'Robert Rodriguez',
 'Simon Davis',
 'Tara Fidler',
 'Toby Yates',
 'Todd Kleparski']

In [457]:
def convertEdtr(row):
    if row=='':
        return 0
    elif row in top1E:
        return 6
    elif row in top2E:
        return 5
    elif row in top3E:
        return 4
    elif row in top4E:
        return 3
    elif row in top5E:
        return 2
    elif row in otherE:
        return 1
    else:
        return 0

merged['grp_Editor'] = merged['EditorName'].apply(convertEdtr)

In [458]:
merged['grp_Editor'].unique()

array([5, 4, 3, 2, 0, 1, 6], dtype=int64)

In [459]:
merged['grp_Editor'].value_counts()

3    188
2    120
4    114
0     60
5     36
1     31
6     28
Name: grp_Editor, dtype: int64

In [460]:
#no we'll move to next step
merged.columns

Index(['budget', 'runtime', 'revenue', 'no:maleCrew', 'no:maleCast',
       'release_month', 'release_dow', 'release_year', 'no:Cast', 'no:Crew',
       'mainGenre', 'no:keywords', 'prod_company', 'no:femCast', 'latestDir',
       'Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'title',
       'Actors', 'recovery_rate', 'crew', 'main_lead', 'co_lead1', 'co_lead2',
       'co_lead3', 'grp_mainLead', 'grp_co_lead1', 'grp_co_lead2',
       'WriterName', 'grp_writer', 'EditorName', 'grp_Editor'],
      dtype='object')

In [461]:
newmodel = merged[['budget','runtime','revenue','no:maleCrew','no:maleCast','release_month','release_dow','release_year', 'no:Cast', 'no:Crew','mainGenre','no:keywords','prod_company', 'no:femCast','latestDir','Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'grp_mainLead', 'grp_co_lead1', 'grp_co_lead2','grp_writer','grp_Editor','title']]

In [462]:
#for one use
#dupFinal2for_prod_cmpny = merged[['budget','runtime','revenue','no:maleCrew','no:maleCast','release_month','release_dow','release_year','no:Cast', 'no:Crew','mainGenre','no:keywords','prod_company', 'no:femCast','latestDir','Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime',
#      'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical','Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'grp_mainLead', 'grp_co_lead1', 'grp_co_lead2','grp_writer','grp_Editor','title','crew','recovery_rate']]

In [463]:
#dupFinal2for_prod_cmpny.to_csv('dupFinal2(for_prod_cmpny).csv',index=False)

In [483]:
x = newmodel.drop(columns = [ 'no:keywords','revenue','no:femCast','release_year','no:maleCrew','mainGenre','title'])

In [500]:
x.columns

Index(['budget', 'runtime', 'no:maleCast', 'release_month', 'release_dow',
       'no:Cast', 'no:Crew', 'prod_company', 'latestDir', 'Action',
       'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime', 'Drama',
       'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'grp_mainLead',
       'grp_co_lead1', 'grp_co_lead2', 'grp_writer', 'grp_Editor'],
      dtype='object')

In [466]:
y = merged['revenue']

In [547]:
x.head(10)

,budget,runtime,no:maleCast,release_month,release_dow,no:Cast,no:Crew,prod_company,latestDir,Action,...,Romance,Sci-Fi,Sport,Thriller,War,grp_mainLead,grp_co_lead1,grp_co_lead2,grp_writer,grp_Editor
0,237000000,162.0,20,12,3,83,153,Twentieth Century Fox Film Corporation,5,1.0,...,0.0,0.0,0.0,0.0,0.0,5,0,0,5,5
1,300000000,169.0,25,5,5,34,32,Walt Disney Pictures,4,1.0,...,0.0,0.0,0.0,0.0,0.0,4,0,0,3,4
2,245000000,148.0,55,10,0,83,155,Columbia Pictures,4,1.0,...,0.0,0.0,0.0,1.0,0.0,4,0,0,3,3
3,250000000,165.0,73,7,0,158,217,Warner Bros.,4,1.0,...,0.0,0.0,0.0,1.0,0.0,4,0,0,3,4
4,260000000,132.0,19,3,2,27,132,Walt Disney Pictures,2,1.0,...,0.0,1.0,0.0,0.0,0.0,2,0,0,5,2
5,258000000,139.0,33,5,1,143,56,Columbia Pictures,3,1.0,...,0.0,0.0,0.0,0.0,0.0,3,0,0,3,3
6,260000000,100.0,8,11,2,13,79,Walt Disney Pictures,2,0.0,...,0.0,0.0,0.0,0.0,0.0,2,0,0,2,2
7,280000000,141.0,22,4,2,72,74,other,4,1.0,...,0.0,1.0,0.0,0.0,0.0,4,0,0,4,4
8,250000000,153.0,24,7,1,49,27,Warner Bros.,4,0.0,...,0.0,0.0,0.0,0.0,0.0,4,0,0,3,3
9,250000000,151.0,84,3,2,152,111,Warner Bros.,4,1.0,...,0.0,1.0,0.0,0.0,0.0,4,0,0,3,3

In [468]:
y.head(2)

0    2787965087
1     961000000
Name: revenue, dtype: int64

In [485]:
newx = pd.get_dummies(x,columns=['prod_company'])
newx.head()

,budget,runtime,no:maleCast,release_month,release_dow,no:Cast,no:Crew,latestDir,Action,Adventure,...,prod_company_Dune Entertainment,prod_company_Legendary Pictures,prod_company_New Line Cinema,prod_company_Paramount Pictures,prod_company_Relativity Media,prod_company_Twentieth Century Fox Film Corporation,prod_company_Universal Pictures,prod_company_Walt Disney Pictures,prod_company_Warner Bros.,prod_company_other
0,237000000,162.0,20,12,3,83,153,5,1.0,1.0,...,0,0,0,0,0,1,0,0,0,0
1,300000000,169.0,25,5,5,34,32,4,1.0,1.0,...,0,0,0,0,0,0,0,1,0,0
2,245000000,148.0,55,10,0,83,155,4,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
3,250000000,165.0,73,7,0,158,217,4,1.0,0.0,...,0,0,0,0,0,0,0,0,1,0
4,260000000,132.0,19,3,2,27,132,2,1.0,1.0,...,0,0,0,0,0,0,0,1,0,0

In [470]:
merged[['latestDir','budget','prod_company','no:Cast','no:maleCast','no:Crew','Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War','grp_Editor']]

,latestDir,budget,prod_company,no:Cast,no:maleCast,no:Crew,Action,Adventure,Aniimation,Biography,...,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,grp_Editor
0,5,237000000,Twentieth Century Fox Film Corporation,83,20,153,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
1,4,300000000,Walt Disney Pictures,34,25,32,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
2,4,245000000,Columbia Pictures,83,55,155,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
3,4,250000000,Warner Bros.,158,73,217,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4
4,2,260000000,Walt Disney Pictures,27,19,132,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,1,2000000,other,9,6,13,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
573,6,1500000,other,19,9,14,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,6
574,6,1000000,other,11,2,41,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,6
575,3,3500000,other,15,5,26,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3
576,3,5000000,other,21,6,57,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2

In [471]:
latestx = merged[['latestDir','budget','prod_company','no:Cast','no:maleCast','no:Crew','Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War','grp_Editor']]

latestestx = pd.get_dummies(x,columns=['prod_company'])
latestestx.head()
latestestx.columns

Index(['budget', 'runtime', 'no:maleCast', 'release_month', 'release_dow',
       'no:Cast', 'no:Crew', 'no:keywords', 'latestDir', 'Action', 'Adventure',
       'Aniimation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Family',
       'Fantasy', 'History', 'Horror', 'Music', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'grp_mainLead',
       'grp_co_lead1', 'grp_co_lead2', 'grp_writer', 'grp_Editor',
       'prod_company_Columbia Pictures', 'prod_company_Dune Entertainment',
       'prod_company_Legendary Pictures', 'prod_company_New Line Cinema',
       'prod_company_Paramount Pictures', 'prod_company_Relativity Media',
       'prod_company_Twentieth Century Fox Film Corporation',
       'prod_company_Universal Pictures', 'prod_company_Walt Disney Pictures',
       'prod_company_Warner Bros.', 'prod_company_other'],
      dtype='object')

In [472]:
latestx.columns

Index(['latestDir', 'budget', 'prod_company', 'no:Cast', 'no:maleCast',
       'no:Crew', 'Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy',
       'Crime', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War',
       'grp_Editor'],
      dtype='object')

In [527]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor


models = [
    ('Linear Regression', LinearRegression()),
    ('Decision Tree Regression', DecisionTreeRegressor()),
    ('Random Forest Regression', RandomForestRegressor(n_estimators=250)),
    ('Gradient Boosting Regression', GradientBoostingRegressor()),
    ('Support Vector Regression', SVR()),
    ('Neural Network Regression', MLPRegressor())
]


# Split the data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(newx, y, test_size=0.2,random_state=5)



for model_name, model in models:
    model.fit(x_train, y_train)
    predictions = model.predict(x_test)
    r2 = r2_score(y_test, predictions)
    mae = mean_absolute_error(y_test, predictions)

    print(model_name + ":")
    print("R-squared score:", r2)
    print("Mean Absolute Error:", mae)
    print()

Linear Regression:
R-squared score: 0.7880444651217033
Mean Absolute Error: 91670095.547445

Decision Tree Regression:
R-squared score: 0.8478141760217982
Mean Absolute Error: 61950328.801724136

Random Forest Regression:
R-squared score: 0.8705085569209382
Mean Absolute Error: 58068940.24124139

Gradient Boosting Regression:
R-squared score: 0.9223419791009395
Mean Absolute Error: 52066104.5580163

Support Vector Regression:
R-squared score: -0.11090776900481969
Mean Absolute Error: 178678274.88627392

Neural Network Regression:
R-squared score: 0.6848348363590553
Mean Absolute Error: 107300765.44537404

In [541]:
x_train, x_test, y_train, y_test = train_test_split(newx, y, test_size=0.2,random_state=5)
model =  GradientBoostingRegressor()
model.fit(x_train, y_train)
predictions = model.predict(x_test)
r2 = r2_score(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)
r2

0.9187869318188155

In [546]:
y_test.tail()#5.10,715,575  ,743,559,607

448      41627431
3      1084939099
248     311256926
311      34227298
524      62076141
Name: revenue, dtype: int64

In [509]:
predictions

array([ 5.10715575e+08,  8.95007071e+07,  7.94903796e+08,  1.13217824e+08,
        1.08210735e+08,  4.56695123e+07,  4.98713793e+08,  1.61350982e+08,
        5.20604083e+07,  3.74313472e+08,  6.73575291e+07,  5.95326468e+07,
        4.24304701e+07,  1.39020296e+08,  1.02848328e+08,  1.34000613e+08,
        2.20162354e+08,  1.10734495e+08, -1.13197481e+07,  1.09673045e+08,
        3.57134056e+08,  3.77695472e+08,  4.24232129e+07,  8.87082980e+07,
        1.22987254e+08,  1.65141637e+08,  3.01268431e+08,  2.29502085e+08,
        4.50738387e+06,  3.09913664e+08,  2.48598926e+08,  1.58117438e+08,
        1.69345146e+08, -1.73194240e+06,  2.06123838e+08,  3.24689671e+07,
        2.71323508e+08,  3.52177905e+08,  9.72683274e+07,  7.06188183e+07,
        1.73928643e+08,  2.51689474e+08,  6.65627265e+07,  3.43244478e+07,
        1.12340198e+08,  4.79623574e+08,  6.08691079e+07,  3.79503222e+08,
        1.39220061e+08,  1.35164265e+08,  3.06183278e+08,  1.40346570e+08,
        6.40747346e+07,  1.07721804e+08,  4.62861556e+07,  3.44777800e+08,
       -8.97008020e+06,  6.01686747e+07,  1.31228526e+08,  6.06757698e+08,
        9.54990198e+07,  8.61446580e+07,  5.69204720e+08,  1.61785079e+07,
        3.58915272e+08,  2.51909315e+08,  2.07772860e+08,  1.06594333e+08,
        5.28428026e+07,  3.23243222e+07,  2.20736190e+08,  1.01041511e+09,
        1.21735072e+08,  1.56650399e+08,  2.09686409e+08,  2.79207080e+08,
        1.67941054e+08,  6.25578597e+07,  1.43528185e+08,  1.40813719e+08,
        1.02412635e+08,  6.41852264e+08,  1.72105510e+08,  1.78226588e+08,
        1.13677714e+09,  3.77361965e+08,  3.11834018e+08,  2.04520243e+08,
        9.26710330e+07,  9.42179967e+08,  2.47772348e+08,  9.80436806e+08,
        2.82649422e+08,  6.37511590e+07,  7.42819276e+07,  6.53306061e+07,
        2.55326934e+08,  1.50421215e+08,  3.13590208e+08,  3.78893930e+07,
        6.12623087e+08,  4.80396057e+07,  5.67474201e+08,  9.43512194e+08,
        3.47054574e+08,  8.32489305e+07,  1.32677525e+08,  1.38920323e+08,
        2.06615938e+08,  5.39184539e+07,  2.03096009e+08,  2.74863936e+07,
        1.04824779e+09,  3.69748844e+08,  4.03364689e+07,  9.52534374e+07])

In [482]:
#which rows are used?
newx.columns

Index(['budget', 'runtime', 'no:maleCast', 'release_month', 'release_dow',
       'no:Cast', 'no:Crew', 'no:keywords', 'latestDir', 'Action', 'Adventure',
       'Aniimation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Family',
       'Fantasy', 'History', 'Horror', 'Music', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'grp_mainLead',
       'grp_co_lead1', 'grp_co_lead2', 'grp_writer', 'grp_Editor',
       'prod_company_Columbia Pictures', 'prod_company_Dune Entertainment',
       'prod_company_Legendary Pictures', 'prod_company_New Line Cinema',
       'prod_company_Paramount Pictures', 'prod_company_Relativity Media',
       'prod_company_Twentieth Century Fox Film Corporation',
       'prod_company_Universal Pictures', 'prod_company_Walt Disney Pictures',
       'prod_company_Warner Bros.', 'prod_company_other'],
      dtype='object')

In [390]:
newmodel.corr()['revenue']

budget           0.750368
runtime          0.332247
revenue          1.000000
no:maleCrew      0.364060
no:maleCast      0.406495
release_month    0.055978
release_dow     -0.216494
release_year     0.030136
no:Cast          0.261178
no:Crew          0.364515
no:keywords      0.161777
no:femCast       0.102793
latestDir        0.210659
Action           0.293821
Adventure        0.498770
Aniimation       0.252482
Biography       -0.105522
Comedy          -0.103390
Crime           -0.166745
Drama           -0.296506
Family           0.055136
Fantasy          0.185537
History         -0.066734
Horror          -0.168744
Music           -0.049223
Musical          0.029296
Mystery         -0.120784
Romance         -0.170947
Sci-Fi           0.193127
Sport           -0.065716
Thriller        -0.049324
War             -0.027347
grp_mainLead     0.190730
grp_co_lead1     0.043602
grp_co_lead2     0.015194
grp_writer       0.314544
grp_Editor       0.246042
Name: revenue, dtype: float64

In [506]:
x.columns

Index(['budget', 'runtime', 'no:maleCast', 'release_month', 'release_dow',
       'no:Cast', 'no:Crew', 'prod_company', 'latestDir', 'Action',
       'Adventure', 'Aniimation', 'Biography', 'Comedy', 'Crime', 'Drama',
       'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'grp_mainLead',
       'grp_co_lead1', 'grp_co_lead2', 'grp_writer', 'grp_Editor'],
      dtype='object')

In [540]:
merged[merged['budget']==260000000]

,budget,runtime,revenue,no:maleCrew,no:maleCast,release_month,release_dow,release_year,no:Cast,no:Crew,...,co_lead1,co_lead2,co_lead3,grp_mainLead,grp_co_lead1,grp_co_lead2,WriterName,grp_writer,EditorName,grp_Editor
4,260000000,132.0,284139100,25,19,3,2,2012,27,132,...,Lynn Collins,Willem Dafoe,Samantha Morton,2,0,0,Karin Silvestri,5,Erik Jessen,2
6,260000000,100.0,591794936,29,8,11,2,2010,13,79,...,Zachary Levi,Donna Murphy,Ron Perlman,2,0,0,Mark Mitchell,2,Tim Mertens,2

In [537]:
x[x['budget']==260000000][:7:10]#876,707,841 , 284,139,100

,budget,runtime,no:maleCast,release_month,release_dow,no:Cast,no:Crew,prod_company,latestDir,Action,...,Romance,Sci-Fi,Sport,Thriller,War,grp_mainLead,grp_co_lead1,grp_co_lead2,grp_writer,grp_Editor
4,260000000,132.0,19,3,2,27,132,Walt Disney Pictures,2,1.0,...,0.0,1.0,0.0,0.0,0.0,2,0,0,5,2

In [520]:
x.shape   799,153,393  2,787,965,087

(577, 33)

In [524]:
x_test.columns

Index(['budget', 'runtime', 'no:maleCast', 'release_month', 'release_dow',
       'no:Cast', 'no:Crew', 'latestDir', 'Action', 'Adventure', 'Aniimation',
       'Biography', 'Comedy', 'Crime', 'Drama', 'Family', 'Fantasy', 'History',
       'Horror', 'Music', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport',
       'Thriller', 'War', 'grp_mainLead', 'grp_co_lead1', 'grp_co_lead2',
       'grp_writer', 'grp_Editor', 'prod_company_Columbia Pictures',
       'prod_company_Dune Entertainment', 'prod_company_Legendary Pictures',
       'prod_company_New Line Cinema', 'prod_company_Paramount Pictures',
       'prod_company_Relativity Media',
       'prod_company_Twentieth Century Fox Film Corporation',
       'prod_company_Universal Pictures', 'prod_company_Walt Disney Pictures',
       'prod_company_Warner Bros.', 'prod_company_other'],
      dtype='object')

In [545]:
column_names = x_test.columns

input_data = [
    {'budget':260000000, 'runtime':132.0, 'no:maleCast':19,'release_month':3, 'release_dow':2,
       'no:Cast':27, 'no:Crew':132,'latestDir':2,'Action':1,
       'Adventure':1, 'Aniimation':0, 'Biography':0, 'Comedy':0, 'Crime':0, 'Drama':0,
       'Family':0, 'Fantasy':0, 'History':0, 'Horror':0, 'Music':0, 'Musical':0, 'Mystery':0,
       'Romance':0, 'Sci-Fi':1, 'Sport':0, 'Thriller':0, 'War':0,'grp_mainLead':2,'grp_co_lead1':0, 'grp_co_lead2':0, 'grp_writer':5, 'grp_Editor':2,'prod_company_Columbia Pictures':0,
       'prod_company_Dune Entertainment':0, 'prod_company_Legendary Pictures':0,
       'prod_company_New Line Cinema':0, 'prod_company_Paramount Pictures':0,
       'prod_company_Relativity Media':0,
       'prod_company_Twentieth Century Fox Film Corporation':1,
       'prod_company_Universal Pictures':0, 'prod_company_Walt Disney Pictures':1,
       'prod_company_Warner Bros.':0, 'prod_company_other':0} # Input values for data point 1
   # Input values for data point 2
    # Add more input data points as needed
]


input_df = pd.DataFrame(input_data, columns=column_names)
#print(input_df) 
#inputt = pd.get_dummies(input_df,columns=['prod_company'])
print(inputt) 
# Make predictions on the input data

predictions = model.predict(input_df) 

# Print the predictions
print(predictions)
r2 = r2_score([[284139100]], predictions)
print(r2)

      budget  runtime  no:maleCast  release_month  release_dow  no:Cast  \
0  237000000    162.0           20             12            3       83

   no:Crew  latestDir  Action  Adventure  ...  Sci-Fi  Sport  Thriller  War  \
0      153          5       1          1  ...       1      0         0    0

   grp_mainLead  grp_co_lead1  grp_co_lead2  grp_writer  grp_Editor  \
0             5             0             0           5           5

   prod_company_Twentieth Century Fox Film Corporation
0                                                  1

[1 rows x 33 columns]
[3.09641724e+08]
nan

C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_regression.py:796: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

In [ ]:
#budget,runtime,no:cast,est.no:crew,rel.month,keywords,prod_company,choose your genres,director,writter,mainLead,colead1,colead2,
#Director,budget,prod_company,mainlead,co_lead1,co_lead2,castno:,malecastno:,genres,no:of:keyword  ^